### ISSUE TITLE
Improvements to elevation profile

### ISSUE THREAD

**Issue by dittaeva** [waymarkedtrails/waymarked-trails-site#108]
While we now have elevation profile code in placing that is working great, the task is such a complex one that there are many things that can be done to improve the code and the feature itself, many of them mentioned in the now closed issue #96:

Feature improvements (better route relations with roles would help for these):
1. Complex routes (Y shapes, non-linear and multiline) are not rendered. See help page entry for more info.
2. Direction of route is determined by elevation of end points (also described in help entry). [I've made a description of how direction should ideally be determined](https://docs.google.com/drawings/d/1K8sgTG2hA5CBd_p3Q4HXipBvYASqE_8FSM2XcNhqZFE/edit).

Code improvements:
1. Store DEM raster code in postgis 2?
2. [Route.js tweak](https://github.com/lonvia/waymarked-trails-site/pull/96#discussion_r2010194).
3. Flot build script (place in contrib).
4. Pack/minimize js code.
5. [Support Spherical Mercator input?](https://github.com/esisa/elevationprofile/issues/1)

**Comment by lonvia** [comment]
Elevation profiles are now available for all routes and direction is determined by the order of relation members. Closing here.
