### ISSUE TITLE
Prefix name of route with route reference in list of routes

### ISSUE THREAD

**Issue by gerdami** [waymarkedtrails/waymarked-trails-site#125]
![waymarkerdtrails-list of routes](https://f.cloud.github.com/assets/1908751/67057/cb518130-5ee4-11e2-975b-ce105d96002b.png)

In the attached list of routes we can see that I have inserted the "ref" tag value into the "name" of the relation. This is bad double encoding. "ref" is the tag for the official reference of the route/relation.

Would it be possible that you display the following

osmc:symbol   -   ref   -   name   

I know that waymarkedtrails already displays the ref instead of the missing osmc:symbol however, the symbol is not a reference.
If the ref is empty, dot not add an extra hyphen.

Thanks.

**Comment by lonvia** [comment]
This is now done. The ref appear on the right side next to the route.
