### ISSUE TITLE
lonvia > waymarkedtrails Change URLs, or advise about new URLs

### ISSUE THREAD

**Issue by dittaeva** [waymarkedtrails/waymarked-trails-site#144]
Link list [on Alexa](http://www.alexa.com/site/linksin;1/lonvia.de).

**Comment by jschleic** [comment]
Your link does not work for me. Probably this issue can be closed.

**Comment by lonvia** [comment]
There are still quite a few old links on the OSM wiki. I started to change them but lost interest after a couple of pages. More critically: wikipedia is linking to old-style relation pages on waymarkedtrails.org (see https://de.wikipedia.org/w/index.php?target=http%3A%2F%2F*.lonvia.de&title=Spezial%3AWeblinksuche and https://de.wikipedia.org/w/index.php?target=http%3A%2F%2F*.waymarkedtrails.org&title=Spezial%3AWeblinksuche). They should forward properly in most cases but I haven't really tested that in practice.

**Comment by lonvia** [comment]
The Wikipedia-Links have gone. I'm giving up on the OSM wiki and close this issue.
