### ISSUE TITLE
Wish: filtering routes without complete=yes

### ISSUE THREAD

**Issue by gorn** [waymarkedtrails/waymarked-trails-site#164]
It would be great it the list of routes can be filtered to only show routes without complete=yes (and maybe somehow emphasize the ones with complete=no) ... this would greatly encourage contribution and would help both mappers (who search for incomplete routs in area) and tourist (to note that there may be info missing)

**Comment by lonvia** [comment]
Most complete routes are not specially tagged in this way, so such a filter would remove too many routes. Furthermore, even semi-mapped routes can be useful.

**Comment by gorn** [comment]
Hi Sarah,  this is Jakub :)

Its funny that you revisited this just before this weekend after 4 years. You are right + it is nice to see how much has changed in 4 years, there is a much more coordination in mapping trails now :), databases, trackers and ... mapping meetings :)))

Nice day
