### ISSUE TITLE
Page speed optimisations

### ISSUE THREAD

**Issue by dittaeva** [waymarkedtrails/waymarked-trails-site#166]
See [desktop](https://developers.google.com/speed/pagespeed/insights#url=http_3A_2F_2Fwaymarkedtrails.org&mobile=false) and [mobile](https://developers.google.com/speed/pagespeed/insights#url=http_3A_2F_2Fwaymarkedtrails.org&mobile=true)

**Comment by lonvia** [comment]
Added ETags and Expiry headers and reduced size of SVGs. I'll pass on the other suggestions.
