### ISSUE TITLE
Problems with the mobile interface

### ISSUE THREAD

**Issue by dittaeva** [waymarkedtrails/waymarked-trails-site#170]
1. One-off location request gives very unprecise location, and with my testing on iPhone proved very unreliable. "Tracking mode" as default when using the button is probably necessary to provide a good enough experience. The location icon on the map should then also show direction, and the geolocate button needs to have an "active" mode (darker?).
2. Better geolocate icon for the WT menu.
3. Highlighting of routes (mouseover on the routes in the route list) does not work well, and is meaningless when the box covers the whole map. Remove, or do other way?
4. To me at least, the small jquery buttons buttons are too hard to click.
5. Route zoom is non-obvious since you do not see the map behind the box. To the user, it might seem like nothing is happening(?)
6. OpenLayers seem to be very sluggish, perhaps because of some "touch event" functionality? (See blue overlay when touching on Chrome on Android.)
7. Box covering the map is very "unelegant". While it does provide consistency, this is probably not necessary. However, the box also covers the map on desktop so a new soltuion should be made for both mobile and desktop at the same time.
8. (Continental/national, etc. is not very relevant on the local level.)

**Comment by lonvia** [comment]
Too many issues together. Closing.
