### ISSUE TITLE
Allow for different base layers

### ISSUE THREAD

**Issue by hholzgra** [waymarkedtrails/waymarked-trails-site#189]
Feature request: allow for different base map tiles more suitable for hiking/biking, like e.g. opencyclemap or hikebikemap (either by providing a predefined list of base maps, or by allowing for adding a custom tile URL in settings)

Personally I'm especially interested in knowing where the next bench might be along the current route, and this is information that's only rendered in the hikebikemap and humanitarian styles AFAICT ...

**Comment by lonvia** [comment]
Different base layers have been possible for a while. I would take requests for adding other base layers but only when the requests come with the explicit permission of the layer provider to use the layer on waymarkedtrails. I don't have the time to hunt for these permissions myself.
