### ISSUE TITLE
allow displaying symbol and text (ID) side by side

### ISSUE THREAD

**Issue by a-pirard** [waymarkedtrails/waymarked-trails-site#190]
Operators assign their itineraries an ID that usually fits in a symbol = an icon ... if it's not too long.
But an [unambiguous national ID](http://cgt.tourismewallonie.be/default.aspx?pg=9e9d7134-fa22-4015-b8d7-768eef2544f2) may/should also be assigned, [download this as a list example](http://cgt.tourismewallonie.be/DownloadHandler.ashx?pg=9e9d7134-fa22-4015-b8d7-768eef2544f2&section=14d6ebef-9a0b-4b47-8254-d5bc6fcc47f5&file=Inventaire+itin%c3%a9raires+touristiques+janvier+2014.pdf).

The national ID such as "SPR07" is the most convenient way to unambiguously reference or search for an itinerary, rather than "red cross on a white background in Sprimont".
But many people like to see the symbol on the map, and it's very nice indeed.

These are reasons (national ID, "local ID too long" and symbol beauty) why I suggest to allow requesting that a second ID be written outside the symbol (attached below, on the right or just near, to your taste).
In fact, that is using both osmc:symbol and the label used when there is no osmc:symbol.

Please note that since 2007 the [South Belgian official signs](http://www.sentiers.be/comprendre-les-chemins-et-sentiers/la-signaletique-et-le-balisage/le-balisage-normalise/) are one of 4 plain colors.  This makes the confusion higher between two itineraries of adjacent municipalities or operators.

Two show [what it would look like, I used a hack](http://www.waymarkedtrails.org/en/?zoom=14&lat=50.5403&lon=5.63978).  I mapped itinerary "SPR07" twice, once with symbol and once without.
Hack deleted due to timeout.

To show the two IDs, a syntax like osmc:symbol=waycolor:background:foreground:text1[;text2]:textcolor is suggested, where text1 defines the symbol text, text2 defines the additional text and where any text = \* to use the same value as ref=\* and = "" to be omitted. 
Any equivalent syntax is of course welcome.

**Comment by lonvia** [comment]
Showing multiple symbols for the same route is not going to happen. It is confusing and clutters the map.

You can either use osmc:symbol with a ref (for the SPR07 example) or the combination of color and name (for the Belgian example).
