### ISSUE TITLE
Incomplete search results - missing the exact search phrase

### ISSUE THREAD

**Issue by zstadler** [waymarkedtrails/waymarked-trails-site#245]
When searching for "Shvil Israel", the [national hiking trail](http://hiking.waymarkedtrails.org/#route?id=282071&map=7!31.3989!35.1981) with this exact name is not included in the search results:

<img width="289" alt="2016-08-06 11_52_35-waymarked trails - hiking" src="https://cloud.githubusercontent.com/assets/1304610/17455812/606b3512-5bcc-11e6-9fcc-2d1c2ff75922.png">

Also, searching for "Shvil", does not produce any result with the word "Shvil":

<img width="289" alt="2016-08-06 12_26_22-waymarked trails - hiking" src="https://cloud.githubusercontent.com/assets/1304610/17455976/10d25f58-5bd1-11e6-825d-daa365687047.png">

**Comment by lonvia** [comment]
The search currently only works over the primary 'name' tag, not over the translations. Something to improve.

**Comment by lonvia** [comment]
Fixed with https://github.com/waymarkedtrails/waymarkedtrails-api/commit/e0929efe48097157d5be1c46dadd41a9bc455559.
