### ISSUE TITLE
Mobile style for help pages

### ISSUE THREAD

**Issue by jschleic** [waymarkedtrails/waymarked-trails-site#248]
The help pages should have a style, that fits for screen widths smaller than 600px.

![wmt_helppages](https://cloud.githubusercontent.com/assets/903453/17566033/12a2e494-5f3a-11e6-8e87-26133d1f6d4b.png)

**Comment by lonvia** [comment]
I wonder if it would make sense to just get rid of the menu there and render one large page.

**Comment by lonvia** [comment]
Works fine these days and looses the menu when the screen is too small.
