### ISSUE TITLE
Foreground symbol orange_dot missing in legend

### ISSUE THREAD

**Issue by Hufkratzer** [waymarkedtrails/waymarked-trails-site#254]
Foreground symbol orange_dot works in waymarkedtrails, but is missing in http://riding.waymarkedtrails.org/help/rendering/osmc_legende

orange_dot is listed on page http://www.wanderreitkarte.de/symbols_en.html
and it is the most used symbol for riding routes in Poland. 

Please add it to the legend so that people know that they can use it.

**Comment by lonvia** [comment]
The symbol page badly needs a redesign. It's not very readable at the moment. I'll do that and add the missing symbol then.

**Comment by Hufkratzer** [comment]
Same for foreground symbol %color%_wheel, see
https://riding.waymarkedtrails.org/#routelist?map=12!52.8938!6.38

**Comment by lonvia** [comment]
42a6f13b0c91eacd5d45128562218d4072de623a refreshes the layout of the osmc help page and adds the missing symbols. The new design will go live in a couple of days.
