### ISSUE TITLE
Adjust osmc:symbol flags for rwn or nwr like it happens for lwn

### ISSUE THREAD

**Issue by AlfredoSP** [waymarkedtrails/waymarked-trails-site#265]
Can we have regional (or national) routes like this
https://hiking.waymarkedtrails.org/#route?id=3980609
with the flag adjusted like the local one like this one below?
https://hiking.waymarkedtrails.org/#route?id=4209954

**Comment by lonvia** [comment]
I have removed the restriction that a CAI shield must be a number. That should make those route shields render in the same style. Note that the change will only go live in a couple of days.
