### ISSUE TITLE
Localized waycolor for lwn over Italy

### ISSUE THREAD

**Issue by AlfredoSP** [waymarkedtrails/waymarked-trails-site#266]
Over Italy only could be have the waycolor of osmc:symbol used by the renderer? The reason is that, in our coutry the hiking routes are depicted in red, if we could apply it for the ones that have osmc:symbol set it would be cool. The rwn and the nwn can remain the same

**Comment by lonvia** [comment]
Would that apply to all lwn ways that have any osmc:symbol set or only a certain subset (e.g. osmc:symbol=red:*)?

In Switzerland we also have different stroking which corresponds to the difficulty of the way (see the Swiss section in https://hiking.waymarkedtrails.org/help/rendering/hikinglocal) . I see that you have added a tag for the CAI difficulty scale. Is that also something you would want to have added? Personally, I would like it as it would essentially mean to simply extend the Swiss color schema south.

**Comment by AlfredoSP** [comment]
Only the ones with osmc:symbol=red*
in few words the ones with waycolor red

I didn't dare to ask for difficulty differention already but if you can it would be very similar to the Switzerland schema with the addition of the red crosses for cai_scale=EEA and over

![image](https://cloud.githubusercontent.com/assets/24659871/23186233/ac2012dc-f886-11e6-9f87-454cc8c4228a.png)

**Comment by AlfredoSP** [comment]
I forgot one thing, I noticed that in Switzerland the red lines are thinner than the violet one. If possible it should have the same thickness otherwise relations with no osmc:symbol, no ref, very little information may look more important that the others while instead is viceversa.
Last but not least, can the cai_scale be used for the violet ones? In this way we will be giving the best information possible

**Comment by Ircama** [comment]
I think that an appropriate filter could be *network=lwn* and *cai_scale* set to specific values (with *type=route*, *route=hiking*), regardless the value of *osmc:symbol* (as *osmc:symbol* [is not a compulsory tag](http://wiki.openstreetmap.org/wiki/CAI#Sentieri)).

I would suggest using red color (#ff0000 or #d30000) to render *lwn* route features tagged with *cai_scale* and would be in favour of the same (or similar) *stroke-width* adopted for Switzerland, which seems also in line with some CAI paper maps. Possibly, the default *stroke-width* used for *network=lwn* routes
(rendered with violet color #db00db) might be too thick.

I add here some references (Italian language) to support the rendering notation mentioned by @AlfredoSP:

- [Classification of hiking routes](http://www.cce.cai.it/files/all_1_classificazione_percorsi_escursionistici.pdf) made by CAI ([Club Alpino Italiano](http://www.cai.it/))
- [Guidelines to tag hiking routes managed by CAI](http://wiki.openstreetmap.org/wiki/CAI#Sentieri)
- [Proposed tagging](http://wiki.openstreetmap.org/wiki/Proposed_features/cai_scale) according to CAI's classification (by AlfredoSP)
- [Guidelines for cartographic symbols related to classification of hiking routes](http://www.caimaresca.it/Sezione/Pubblicazioni/Linee%20guida%20cartografia%20escursionistica.pdf): check page 5 of 18. This is a document I found online produced by CAI which proposes a standardization of the symbols in hiking maps and a quality certification model for cartographic products dedicated to hiking

Other than 'T', 'E', 'EE' and 'EEA:*' levels, there is also the 'EAI' one (Expert Hickers with Snow Equiment), which could have smaller *stroke-dasharray* than 'E', with blue color (#0000ff).

Notice that the possible values for *cai_scale* are the following (and, above all, EEA includes 5 degrees of difficulty):

cai_scale=T
cai_scale=E
cai_scale=EE
cai_scale=EAI
cai_scale=EEA:F
cai_scale=EEA:PD
cai_scale=EEA:D
cai_scale=EEA:MD
cai_scale=EEA:E

**Comment by AlfredoSP** [comment]
Just a few comments on your notes:

There are areas where the paths have a ref code established but they are not properly painted yet.
For these cases we use on our paper maps the ref color for the ones properly painted and a gray (or other color) for the others.

in OSM we distinguish between these cases assigning osmc:symbol. if it's set, it'ckns properly painted (therefore red) otherwise different color.
osmc:symbol is not a compulsory tag but we use it in this way.

Therefore is possible I would render red the ones with osmc:symbol and in violet the others

The thickness looks ok the way it is now in violet, I would not reduce it like in Switzerland because the result is less visible.

About the EAI, your suggestion sounds good to me.

**Comment by lonvia** [comment]
cai_scale=EAI shouldn't be route=hiking at all, that's route=snowshoe or similar. These are then rendered on the winter map.

Having played around with that a bit yesterday. it turns out that to get a similar scaling to Switzerland, I have to do T = line, E/EE = dashed, EEA:* = dotted. I'm aware that this isn't exactly what you are used from your maps but I can't use the same styling for neighbouring countries and then have them mean different things. In particular not with something as potentially dangerous as the difficulty of a trail.

**Comment by AlfredoSP** [comment]
I think that what you suggest is ok and it's already a big step ahead.
I agree about the EAI as well, they should not be hiking therefore they should be rendered in the winter map.

**Comment by lonvia** [comment]
So I ended up using different forms of dash to distinguish between E and EE as explained now in [the Italian section for localised rendering](https://hiking.waymarkedtrails.org/help/rendering/hikinglocal). The results should be visible in a couple of hours. The database is still busy recomputing the routes.

I need to give the line width some more thought. The red lines might be too thin now for high-res screens. But that is a bit of a separate issue.

**Comment by Ircama** [comment]
It is quite a nice work, thanks.

I also appreciate that all modifications are made in one commit: this helps addressing any possible further suggestion more specifically.

I might return to the consideration also reported by @AlfredoSP that the default stroke-width related to *network=lwn* routes (the one rendered with violet color #db00db and now referring generic paths) looks more relevant than the officially tagged routes, but maybe it is too early now and we need to revise this new rendering for some time on different places before new comments.

**Comment by lonvia** [comment]
I have slightly increased lne width. Let's see how this works out.

**Comment by AlfredoSP** [comment]
I see the new presentation taking place and I like it a lot. To be perfect the EEA should be done with + + + + but if I remember well in previous conversation this was not easy to obtain. I have one question, as the new lines appear the ref doesn't get displayed anymore, is this a temporary status as it's computing the routes or it's a side effect? If the latter it should be changed because the ref is important. It should be displayed within a rectangle of the same line of the route. It should look different enough from the one displayed by osmc:symbol

**Comment by lonvia** [comment]
The shields certainly should be there, with a red border even. I need to look into what is going on there.

**Comment by lonvia** [comment]
Shields seem to be working okay with newly updated data, e.g. https://hiking.waymarkedtrails.org/#?map=14!44.0531!10.2464 . So I suspect that the missing shields are artefacts from when I tried to force an update in a rather crude way.
