### ISSUE TITLE
Recommend offline alternative

### ISSUE THREAD

**Issue by matkoniecz** [waymarkedtrails/waymarked-trails-site#267]
As I undrestand architecture of this software menas that making offline version that would work on a mobile device means starting from the scratch.

But would it be possible to mention in documentation existing alternatives?

**Comment by lonvia** [comment]
The main issue with an offline version is that you need an offline base map. waymarkedtrails does not provide that. I don't think there is anything specific that can be recommended. There are a couple of outdoor apps that do have route information. I wouldn't know which ones are particularly good. For Android, I use OsmAND but that has enough quirks with the route display that I'm not entirely comfortable recommending it. For other OSses I have no idea.

**Comment by gerdami** [comment]
For hiking, I often use OsmAnd with its offline maps **and** WaymarkedTrails as overlay, thank you.

**Comment by nubenum** [comment]
I have been using Maps.Me which is simple yet quite good (and vector-based). It can import KML tracks by just opening them with the app (on Android at least). So I often just download the tracks I need from WT. Since today it is possible to directly download KML without the detour via GPX (which Maps.Me doesn't support).

**Comment by matkoniecz** [comment]
> There are a couple of outdoor apps that do have route information. I wouldn't know which ones are particularly good

After long testing I ended using mapy.cz and I am quite happy about it.

**Comment by lonvia** [comment]
This is really rather something for a wiki page. Doing a comparison of the different mobile offline router is outside the scope of this project.
