### ISSUE TITLE
Monadnock-Sunapee Greenway doesn't show elevation profile

### ISSUE THREAD

**Issue by iamkrzys** [waymarkedtrails/waymarked-trails-site#277]
I have recently finished marking Monadnock-Sunapee Greenway: https://hiking.waymarkedtrails.org/#route?id=3888871&map=10!43.0887!-72.1072
As far as I can tell all segments of the trail are connected now, however, the elevation profile is grayed out for the trail and gpx is a set of track segments that are not ordered in the same direction.  Any ideas?

**Comment by lonvia** [comment]
When waymarkedtrails creates the GPX and the elevation view, it uses the ways in the order they are listed in the relation. So the members of the route need to be sorted. The easiest way to achieve that is to use JOSM: load the route into JOSM, open the relation editor and click on the little 'A..Z´  button. If the route is complete then it will put the ways in the right order easily. You can see then an unbroken line right next to the members.

In the case of your route, you'll see that there is still a tiny mistake near [Seaver Road](https://www.openstreetmap.org/way/509357124).

**Comment by iamkrzys** [comment]
Thank you for a quick reply and apologies for wasting your time!  I guess I should try using JOSM (I have always been a Potlach person.)

**Comment by lonvia** [comment]
The sorting requirement is actually quite new, waymarkedtrails used to sort by itself until recently. I have now partially reverted to the old behaviour: if the route segments yield a single linear route, then waymarkedtrails will still sort it if necessary. For all other cases the order of the relation is used.

I still recommend sorting the route. Then you still get a useful elevation profile and GPX, even when somebody accidentally breaks the relation, for example, when fusing ways.
