### ISSUE TITLE
Feature request: Trail Grade Profile

### ISSUE THREAD

**Issue by iamkrzys** [waymarkedtrails/waymarked-trails-site#279]
While elevation profile can give map viewer some sense of relative steepness of the trail, it does not reflect actual steepness due to varying scale of x-axis in the profile.

Would it be possible to add support for displaying trail grade ( https://en.wikipedia.org/wiki/Grade_(slope) ) in addition to elevation profile? In U.S. grade (given in percentage points) is commonly displayed on steep road section.

**Comment by lonvia** [comment]
The elevation information we have available (SRTM) does not have a sufficient resolution to determine accurate grade information, I'm afraid.
