### ISSUE TITLE
osmc:symbol background

### ISSUE THREAD

**Issue by gorn** [waymarkedtrails/waymarked-trails-site#283]
Hi Sarah,

can you suggest what value one should use when the osmc:symbol has no background? Currently I use something like 

osmc:symbol = blue:none:blue_pointer

but it does not produce good results on your map. Compare [this blue route](https://hiking.waymarkedtrails.org/#route?id=7226181) and [this yellow route](https://hiking.waymarkedtrails.org/#route?id=7315523). Both are pointer with no background. In the yellow case I used

osmc:symbol = blue:white:yellow_pointer

so the icon shows on your map, although it's mapping fore renderer. I would prefer to have a way to tag correctly non-existing border.

Thanks

**Comment by lonvia** [comment]
Just leave the background empty. So in your example it should be: blue::blue_pointer.

**Comment by gorn** [comment]
Ok, thanks. Will try this, there is another issue, but I will post it separately.
