### ISSUE TITLE
blue:white:blue_bar showing as violet

### ISSUE THREAD

**Issue by gorn** [waymarkedtrails/waymarked-trails-site#284]
It seems to me that rendering of blue:white:blue_bar is incorrect now. For example at

https://hiking.waymarkedtrails.org/#route?id=1559732

it seems to render as violet bar on white background. Using Firefox 52 / Debian

**Comment by lonvia** [comment]
That was a comma where it should not be. Fixed now but the old symbol might occasionally still show up on lower zoom levels until the tiles get rerendered.
