### ISSUE TITLE
New feature : state=proposed

### ISSUE THREAD

**Issue by axelos** [waymarkedtrails/waymarked-trails-site#286]
Hello,

The relations with tag state=proposed no affiched in the map.
Possible add feature button for activate the affichate relations with state=proposed ? (disable per default)

Cordially, excuse for my english basic.

**Comment by lonvia** [comment]
It was a conscious decision to not show proposed routes as the map is mainly for users of routes. They should not be surprised to find that the route they have chosen does not even exist.

So showing proposed routes will never happen. Sorry. (Personally, I believe that these routes don't even belong into OSM but this is a different discussion.)
