### ISSUE TITLE
Use wikidata=*

### ISSUE THREAD

**Issue by KTim21** [waymarkedtrails/waymarked-trails-site#287]
Currently only wikipedia=* is used to display Wikipedia-Links. If this is not avaiable, you could use [wikidata=*](http://wiki.openstreetmap.org/wiki/Key:wikidata).

**Comment by lonvia** [comment]
Sorry but this is not going to happen. Linking to wikidata is not much use for the end user and parsing wikidata information is outside the scope of this project.
