### ISSUE TITLE
Use route colors when provided

### ISSUE THREAD

**Issue by OndrejSpanel** [waymarkedtrails/waymarked-trails-site#292]
In some countries (Czech republic, `operator=cz:KČT`) the hiking routes use color codes. Currently they are rendered like this:

![image](https://user-images.githubusercontent.com/6927223/36397441-1502ed88-15c3-11e8-9a6f-6fa891e9db92.png)

This is not bad, but it would be much better if the color would be used for the route itself, as this is the common way how this is rendered on hiking maps, like mapy.cz:

![image](https://user-images.githubusercontent.com/6927223/36397500-59d13d3e-15c3-11e8-8752-7dcd15f54fff.png)

It seems even [key:osmc:symbol](https://wiki.openstreetmap.org/wiki/Key:osmc:symbol?uselang=en-US) assumes such rendering:

> osmc:symbol=waycolor:background
> - waycolor - Name of the color in which the route path itself should be painted

I have seen a mention about such style already implemented for Norwich in the [Localized Rendering](https://cycling.waymarkedtrails.org/help/rendering/hikinglocal) page.

Note: the route usually do not have any other name or designation that a color, therefore it is usually not necessary to render any other markers or labels over it.

**Comment by jschleic** [comment]
Please have a look at the discussion at #161 ; I think this one is a duplicate.
