### ISSUE TITLE
The same osmc:symbol rendered in three different ways

### ISSUE THREAD

**Issue by Janjko** [waymarkedtrails/waymarked-trails-site#295]
[On this part of the map](https://hiking.waymarkedtrails.org/#?map=14!44.3219!15.4796) there are three different versions of rendering the same osmc symbol that goes like this:

osmc:symbol=red:white:red_circle

On the left there is [one with a thin border](https://hiking.waymarkedtrails.org/#route?id=5573437), in the middle there is [one with a thicker one](https://hiking.waymarkedtrails.org/#route?id=6089103) (looks the closest to the real world), and on the right there is [one that is fully filled in](https://hiking.waymarkedtrails.org/#route?id=5572545).
It's the standard [Knafelčeva markacija](https://www.google.com/search?q=Knafel%C4%8Deva+markacija&tbm=isch) that is used a lot in this part of Europe. Is this the best way to tag this symbol?

Thanks for an exquisite map!

**Comment by lonvia** [comment]
Two of the routes have a `jel` tag. This is preferred over the `osmc:symbol` tag where existing. The symbols follow this wiki description: https://wiki.openstreetmap.org/wiki/Key:jel

**Comment by Janjko** [comment]
Thanks! Didn't know those existed. Renamed them to jel:disused, so as not to just delete them.

**Comment by Hufkratzer** [comment]
The horse icons for jel= klo (blue) and slo (yellow) don't seem to work, see:
https://riding.waymarkedtrails.org/#route?id=6078028 (slo)
https://riding.waymarkedtrails.org/#route?id=7314457 (klo)

jel=flo is not on the wiki page but used, seems to mean black horse, also doesn't work:
https://riding.waymarkedtrails.org/#route?id=8222292

Related: https://github.com/waymarkedtrails/waymarked-trails-site/issues/203
