### ISSUE TITLE
Italian CAI style

### ISSUE THREAD

**Issue by cascafico** [waymarkedtrails/waymarked-trails-site#298]
Hello,
few days ago I realized we have a nice style when relation are tagged Club Alpino Italiano (CAI); it is rendered differently based on difficulty (cai_scale OSM tag). 

Which criteria is applied?
Does it consider cai_scale both for relation and way?
Is there a priority between these two objects?

By the way, is there a sandbox WMT instance to experiment tag/styles combinations?

**Comment by amadvance** [comment]
Locazied rendering is documented in this help page: https://hiking.waymarkedtrails.org/help/rendering/hikinglocal

**Comment by lonvia** [comment]
Indeed.

**Comment by cascafico** [comment]
> Locazied rendering is documented in this help page: https://hiking.waymarkedtrails.org/help/rendering/hikinglocal

I was aware of the mentioned page, "Routes marked with network=lwn, osmc:symbol=red:.. and a cai_scale tag will be recognised [...]". Just wanted to be sure it is applied on OSM relations ("Routes") only, standardizing different difficulties in a single symbol. 
Would it be cumbersome applying style on ways appropriately tagged?

**Comment by lonvia** [comment]
This site is for routes only.
