### ISSUE TITLE
Feature request: basemap type URL parameter

### ISSUE THREAD

**Issue by Raruto** [waymarkedtrails/waymarked-trails-site#299]
for reasons similar to: https://github.com/waymarkedtrails/waymarked-trails-site/issues/227
I think it would be more convenient to also use url parameters when settings on the map (as is done in the localStorage), especially when you are going to **share the opentopo map type** with someone else who does not know waymarkedtrails.org (and its features).

**Comment by lonvia** [comment]
Same answer as in #227. I prefer to leave the choice to the taste of the individual user.
