### ISSUE TITLE
Guidepost clickable image-tag

### ISSUE THREAD

**Issue by pududuss** [waymarkedtrails/waymarked-trails-site#301]
If a Guidepost has a image tag, the content shoud be provided as a link.
For example:
https://hiking.waymarkedtrails.org/#guidepost?id=3734997144
https://www.openstreetmap.org/node/3734997144

This would lead to a simple planning tool, and would made an easy way to represent the destinations from a single guidepost.

The following umap demonstrates the desisred behaviour:
http://umap.osm.ch/en/map/wanderwegweiser_514#15/46.9753/8.2876

**Comment by alpter** [comment]
definetly agree... it would make a nice addition for survey and planning hiking ....

**Comment by lonvia** [comment]
As a minimal precaution, this only works with image tags with full urls (i.e. starting with http(s)://).

**Comment by pududuss** [comment]
Thanks!
