### ISSUE TITLE
Routes panel does not mention "national"

### ISSUE THREAD

**Issue by boothym** [waymarkedtrails/waymarked-trails-site#303]
In the routes panel on the right hand side, there are headings for:

- continental (iwn)
- **other (nwn)**
- regional (rwn)
- **other (lwn)**

The first other for nwn should really have a heading of "national" and the second other for lwn should probably have "local" as well.

**Comment by lonvia** [comment]
I see 'national' as expected. Please post a specific link where you see that and let me know what languages you have set in your browser.

**Comment by boothym** [comment]
Browser (tested on both Firefox and Chrome in Win10) set to en-GB according to the request headers. 
https://hiking.waymarkedtrails.org/#routelist?map=10!55.7232!-2.9323
![wmt](https://user-images.githubusercontent.com/16965772/48944573-2d6ddf00-ef1f-11e8-80cb-fd8da3755114.png)

**Comment by lonvia** [comment]
I see. That's the British National Trails. They have their very own category. I'll have a look at fixing that.

About the 'other(lwn)': these are intentionally called 'other' because it also includes routes that have no network tag at all.

**Comment by lonvia** [comment]
Fixed now with the new database.
