### ISSUE TITLE
Document the API endpoints

### ISSUE THREAD

**Issue by carlos-mg89** [waymarkedtrails/waymarked-trails-site#304]
Hi!

I'm planning on setting up a copy of the WaymarkedTrailsSite, and for this I'm very interested on consuming the API it will set up, so I can directly obtain the related information.

I have seen the documentation to install the server, but I cannot figure out a clear way of consuming the API methods by reading the API folder files. At the moment, I'd more than happy with knowing the list of available routes in a given area (by a bounding box, for example), or to get a list of all the hiking routes (this isn't a bad idea at all, if it's possible to paginate the results, so I could process every route and perhaps do other work related to it, like getting which countries and regions the route is crossing).

Thanks in advance and big thanks for this awesome project :)

**Comment by carlos-mg89** [comment]
For anyone whiling to combine forces and document the API endpoints, here is a start:

- /api/list/by-area?bbox=207854,5010674,395419,5154426&limit=100

  - Description: Gets a list of OSM relations, that are searched in the area given by the bounding box
  - bbox: You can use http://tools.geofabrik.de/calc/#type=geofabrik_standard&bbox=-19.42432,26.991208,4.606796,43.878902&tab=2 this tool to generate the Web Mercator projection for the required bounding box.
  - limit: The amount of results (the maximum in the API is 100 results, although you can edit the api/listings.py file to change this line `limit = self.num_param(limit, 20, 100)`. The third parameter sets the maximum value.
- /api/list/by_ids?ids=your_relation_ids_separated_by_commas
  - ids: has a maximum of 100 values placed as well
- /api/list/search
  - query: To search relations that contain the given qury
  - limit: 100 by default is the maximum again
  - page: By default you will see the page 1, maximum is 10

- /api/details/relation/2163936
  - Def: Get the details of a given relation
  - id: Mandatory parameter. It's the ID of the relation.

**Comment by lonvia** [comment]
There now is the documentation that is generated by default by hug: https://hiking.waymarkedtrails.org/api/

Formatting could be better but at least it's a start. I probably won't do more.
