### ISSUE TITLE
What is a wayset?

### ISSUE THREAD

**Issue by Hufkratzer** [waymarkedtrails/waymarked-trails-site#310]
When I select [this downhill piste](https://slopes.waymarkedtrails.org/#route?id=478298846&type=wayset&map=15!47.6028!10.5023)  on top of the detail view is a link [wayset 478298846](https://www.openstreetmap.org/wayset/478298846). This page does not exist. How is a wayset defined? Where is it documented?

P.S.: I was asking because I want to find out if such waysets may possibly be used also in the horse riding map to show ways tagged with highway=bridleway/horse=designated/horse=yes.

**Comment by datendelphin** [comment]
Those waysets are only created to collect all ways of a slope, because slopes can be tagged without a relation. There should not be a link to OpenStreetMap because they do not exist in the source OpenStreetMap data.

**Comment by Hufkratzer** [comment]
For the example mentioned above the the link could perhaps be "[way 478298846](https://www.openstreetmap.org/way/478298846) ff" because this is one way of the wayset.

In [this](https://slopes.waymarkedtrails.org/#routelist?map=15!47.6124!10.5044) slope list the 2nd entry (with blue dot) and the 3rd entry (with black dot) seem to lead to the same [wayset 478298844](https://www.openstreetmap.org/way/478298844) ff. The 3rd line seems to be wrong (black dot in list, but blue dot in detail view).

Anyway, if these waysets are an internal feature of WMT I think they may also be used in the horse riding map to show ways that are not members of relations of type route=horse but tagged with highway=bridleway/horse=designated/horse=yes. This would be helpful. We have
- 1.5k route=horse
- 40k highway=* + horse=designated
- 83k highway=bridleway
- 298k highway=* + horse=yes

The waysets would reduce the number of separate horse related ways on the map; It may not be necessary to distinguish between the different kinds of highways because this is also not done for the menbers of the horse riding routes.

Compare / related:
- http://mijndev.openstreetmap.nl/~peewee32/paard/ruiterpadenOSM.html 
- https://github.com/waymarkedtrails/waymarked-trails-site/issues/220#issuecomment-145664092

**Comment by lonvia** [comment]
Sorry, but no. waymarkedtrails is for showing routes, it is not a fully featured riding map. The slope map is a bit of the odd one out here but it will remain the exception.
