### ISSUE TITLE
Rendering of overlapping hiking routes in Switzerland

### ISSUE THREAD

**Issue by rbuffat** [waymarkedtrails/waymarked-trails-site#312]
I assume this site follows the "[Alpine Paper Maps (Austria)"](https://wiki.openstreetmap.org/wiki/Key:sac_scale#Rendering) rendering style, where mountain hiking routes (with white-red-white signalization) are rendered with a dashed red line. The problem arises when multiple hiking routes overlap. This can lead to situations were mountain hiking routes are rendered as solid red, which would indicate "normal" hiking routes.  Such a case can be seen here: https://hiking.waymarkedtrails.org/#map=18!46.1914!9.0515

Possible solutions would be to make the rendering aware of multiple routes, respectively switch to a rendering that does not encounter this behavior (such as the Swiss yellow, red or blue color scheme).

**Comment by lonvia** [comment]
Hiking styles are described [in the help page](https://hiking.waymarkedtrails.org/help/rendering/hikinglocal).

The routes of the Swiss hiking network must never overlap per definition. I'd consider the mapping in that example wrong. (I also consider it wrong that these relations all have names. They have no official names. The name tags are just made-up itineraries.)

**Comment by rbuffat** [comment]
@lonvia Thanks for the quick reply! 

> The routes of the Swiss hiking network must never overlap per definition.

Is this a definition by the OSM community or by the Swiss hiking associations? Regardless, I don't think it holds true in "reality". 

Here is a link to the description of the guideposts in Switzerland: https://www.wandern.ch/de/signalisation (Unfortunately only in German, respectively French or Italian if you sitch the language at the top right (FR / IT)).  The guideposts have this white plate in the middle with the name of the location and the elevation.  In the yellow part, the topmost name indicates the next such white locations. The names below represent further stops on the same route. A black line indicates if the routes will split further away.

Thus logically for me, it would make sense to have a relation between the location of the guidepost and the top most name. (E.g. from Alpthal to Butzi on the Guidepost of the previous link). However, in reality, there are some issues with that: 
- The names of white labels are not unique. [E.g. Oberhofen](https://hiking.waymarkedtrails.org/#settings?map=18!46.7303!7.6707) Photo of guideposts: https://imgur.com/a/cPxSn4r
- Such relations are not always symmetrical. There could be other guideposts in between that are not shown. Such as [Oberhofen - Burghalde - Oberi Allmit ](https://hiking.waymarkedtrails.org/#settings?map=16!46.7342!7.6794) Photos of guideposts: https://imgur.com/a/cxqod0W
- Such relations can overlap in the middle. E.g. the above example of the relation Monti di Artore -> Motto della Croce, respectively Monti di Ravecchia -> Motto della Croce. Overlapping means thereby that they share the same path until a guidepost without a white label. Photos of the two guideposts with a white label and the guidepost in the middle without a white label separating the routes: https://imgur.com/a/0MQsZLx

**Comment by lonvia** [comment]
I am quite sure because I am the person who proposed the tagging for the Swiss route system. The idea behind it is that it is a node network. That means you don't really have routes in the classical sense going from A to B via C. You have points and connections between these points. In Switzerland the points are guideposts. They are often but not always named. Each relation should now be exactly the way between two points, i.e. it never should go past a point where two hiking routes meet. For practical reasons, we've ended up concatenating adjoining relations to keep the number of relations down a bit. But still there must be only one relation per way because there are no multiple routes.

By the way, the relations should not have a name either because in a node network it is the nodes that are named, not the connection in between them. This is something we did agree on when initially discussing the tagging. The current state of affairs with 'name', 'osmc:name' was an undiscussed mass edit of a single user 'hecktor'. It is especially unfortunate as there actually are some routes with have a name (e.g. [Strada Alta](https://hiking.waymarkedtrails.org/#route?id=1152292)) which now can no longer be distinguished from these made up names.

**Comment by rbuffat** [comment]
I think from a "data modeling" perspective you are completely right, as ways belonging to multiple hiking relations do not contribute any additional information.

However, the Swiss hiking network (according to the wandern.ch link I posted above) refers to nodes as the guideposts with the white labels. The same definition is found in the [OSM wiki:](https://wiki.openstreetmap.org/wiki/Switzerland/HikingNetwork) `The hiking nodes are labeled guideposts. Each of them contains a small white signboard with the name of the place (usually open fields names) and the elevation over mean sea level.`
respectively in the german wiki: `Als Knoten dienen benannte Wegweiser, also solche, die zusätzlich zu den Weisern ein kleines weisses Schild haben, dass den Namen des Ortes enthält sowie die Höhe über Meeresspiegel. Sie sollten wie in Proposed_features/Guidepost empfohlen getaggt werden.`.

Creating relations between guideposts with the wite labels leads to potential multiple hiking relations per way. (As in the Monti di Artore -> Motto della Croce, respectively Monti di Ravecchia -> Motto della Croce example).

**Comment by lonvia** [comment]
Yes, I know that it says 'labelled guidepost'. As I said: I wrote that. Should have changed that when realising after a couple of weeks later that they are less often labelled than I initially thought. How many are labelled and what is exactly written as a direction also differs significantly from canton to canton.

The core issue is still that you are trying to create routes where there are none. Switzerland has a network of waymarked paths, that's all. You cannot map them in the same way as, say the Via Alpina. The goal of the proposal was to propose a way to map the entire network using linear, non-overlapping relations.

I would change the wiki page to make that goal more clear but I'm no longer actively involved in mapping of Swiss hiking routes. Please open up a discussion on the Swiss mailing list.

I'll leave the issue open as there is an obvious bug in the software.

**Comment by rbuffat** [comment]
This issue is still present. Is this a won't fix?

**Comment by rbuffat** [comment]
> I'll leave the issue open as there is an obvious bug in the software.

Is it possible to open this issue again? As above described it is an obvious bug in the software. There are multiple occasions were paths have multiple hiking routes assigned, and they are rendered wrong.
