### ISSUE TITLE
Display of “direction_*”-tags on guideposts broken

### ISSUE THREAD

**Issue by robhubi** [waymarkedtrails/waymarked-trails-site#313]
I‘m 100% sure that I’ve seen the visualization of direction_=*”-tags a few days ago (~ May 8th). But today – nothing. See attached example from Zürich Münsterbrücke:

![WMT_GP](https://user-images.githubusercontent.com/38103976/57586896-ca87f880-74fc-11e9-9b79-b6c59819de1f.jpg)

[Link1](https://cycling.waymarkedtrails.org/#guidepost?id=5499266342&map=18!47.369!8.5431)
 [Link2](http://osm.mueschelsoft.de/destinationsign/example/index.htm) Node Id: 5499266342

I’m very missing this feature :-(

P.S.: Win 7, 64 bit; Firefox 66.0.5 (32-Bit); Internet Explorer 11.0.9600.19326

**Comment by mueschel** [comment]
Hi robhubi,
thanks for reporting. There was a connection error to the data server this evening. I fixed it and the destination sign display works again.

**Comment by lonvia** [comment]
Many thanks for fixing this so quickly @mueschel.

**Comment by robhubi** [comment]
Thanks, I’m happy again :-)

 

Von: mueschel [mailto:notifications@github.com] 
Gesendet: Montag, 13. Mai 2019 01:48
An: waymarkedtrails/waymarked-trails-site <waymarked-trails-site@noreply.github.com>
Cc: robhubi <robgruebler@gmail.com>; Author <author@noreply.github.com>
Betreff: Re: [waymarkedtrails/waymarked-trails-site] Display of “direction_*”-tags on guideposts broken (#313)

 

Hi robhubi,
thanks for reporting. There was a connection error to the data server this evening. I fixed it and the destination sign display works again.
