### ISSUE TITLE
problems with background symbol "round"

### ISSUE THREAD

**Issue by Hufkratzer** [waymarkedtrails/waymarked-trails-site#314]
If you look at https://hiking.waymarkedtrails.org/#route?id=5396081 the symbol does not correspond to 

> osmc:symbol=yellow:brown_round:yellow_dot:G:white

It looks like
![ttt1](https://user-images.githubusercontent.com/5958184/62076412-e0799f80-b247-11e9-9c79-6fc59d53c249.png)

In the preview it looks different:
![ttt2](https://user-images.githubusercontent.com/5958184/62076529-30f0fd00-b248-11e9-8633-fef855ebd8a7.png)

In the preview for 

> osmc:symbol=yellow:brown_round:yellow_dot

 (without the text "G") the "yellow_dot" is missing:
![ttt3](https://user-images.githubusercontent.com/5958184/62076663-8af1c280-b248-11e9-89d5-2f9bfe475095.png)

**Comment by lonvia** [comment]
That's two completely different issues.

The KCT symbol always takes precedence. There was a request in #257 to change that but I never got a response to where that would be needed.

I see the issue with the round background. I need to look into that.

**Comment by lonvia** [comment]
Fixed the background issue in e6a89af7d71bfe96dadd2d766bf945e385de1046.
