### ISSUE TITLE
Feature request: render "bike lanes" even if not part of a relationship

### ISSUE THREAD

**Issue by rjgambrel** [waymarkedtrails/waymarked-trails-site#316]
An important type of cyclist friendly way here is a "bike lane" which is designated on the ground or with signs. OSM tags used are:  highway=<doesn't matter what>  bicycle=designated  cycleway=lane. 

These are often not part of a relationship. OpenCycleMap renders these as blue lines on the left and/or right side of way (depending on other tagging).

I believe that waymarked trails (cycling) should also render these in some distinctive way (the OpenCycleMap approach is fine.)  You render well other non-relationship cycling ways (such as highway=cycleway  bicycle=designated) even if they are not part of a relationship. You should also render well bike lanes as requested above.

Thank you. Am new to Git Hub & Waymarkedtrails, so please be patient if this has already been discussed and rejected. Would like to know why rejected though, if possible.

**Comment by lonvia** [comment]
waymarkedtrails is not the right place for that. It really only provides the information about the routes. The underlying map is just the standard map as it can also be found on openstreetmap.org. It may show some other cycle infrastructure. Which one exactly is beyond the control of the site.
