### ISSUE TITLE
The site is not refreshing the changes done in the last days ( a week more ore less)

### ISSUE THREAD

**Issue by AlfredoSP** [waymarkedtrails/waymarked-trails-site#317]

**Comment by AlfredoSP** [comment]
Check this relation for example
https://hiking.waymarkedtrails.org/#route?id=9759138

**Comment by lonvia** [comment]
This only fixes future updates. Still trying to figure out how to fix past updates.

**Comment by lonvia** [comment]
Hopefully the old ones are fixed now, too.
