### ISSUE TITLE
Renaming of MTB Routes impossible

### ISSUE THREAD

**Issue by BergListe** [waymarkedtrails/waymarked-trails-site#318]
I looks like as if it's impossible to rename a route by changing its ref. 
I corrected some routes in Spain that had the operator added to the ref attribute instead of the operator attribute. After the correction the route name (abbreviation of the former ref value) doesn't change to the new ref value.

See this link for an example: 
https://mtb.waymarkedtrails.org/#route?id=3330263&map=16!38.7233!-0.2008

Am I doing something wrong or is this wanted a feature?

**Comment by BergListe** [comment]
Looks like #317 addresses the same issue.

**Comment by lonvia** [comment]
Yes, that's the same.
