### ISSUE TITLE
Render walking node networks from a higher zoomlevel for The Netherlands

### ISSUE THREAD

**Issue by pelderson** [waymarkedtrails/waymarked-trails-site#320]
While the idea of a separate network-tag for node networks simmers, could the walking node networks be rendered from a higher zoomlevel for the Netherlands? Routes first visible at zoom 12 would make the map much better. Numbered nodes at zoom 13 like it is now, that's fine.

_Originally posted by @pelderson in https://github.com/waymarkedtrails/waymarked-trails-site/issues/201#issuecomment-520127200_

**Comment by pelderson** [comment]
See the issue of the original post illustrating why.

**Comment by lonvia** [comment]
In theory, yes. In practise it is only possible to filter all network=nwn in the Neatherlands because the network relations don't have any other special tags to distinguish them by. Any nwn routes that are not part of the route network would disappear as well as collateral damage.

**Comment by pelderson** [comment]
Thanks for the quick response! It’s about rwn, not nwn. Normal routes in The Netherlands are lwn, nwn or iwn.
In The Netherlands, network=rwn has been completely hijacked for the walking node networks. The rest should all be lwn, nwn and iwn. This is by national community agreement. I can easily find and retag the few routes that do not comply with this, can’t be much so will be done fast.

I can check again that there are no objections in our community. Could you set a date to make it happen if consensus is confirmed and I have checked all other routes?

(I am still working on the idea of a separate network tag for node networks, in principle the community agrees but people want the network checking site to pilot it first, which will take considerable time)

Fr Gr Peter Elderson

**Comment by lonvia** [comment]
If you say that there is community census that rwns belong to the node network then that is enough for me. I'll look into it but I can't give you a deadline when exactly I'll have time.

**Comment by pelderson** [comment]
Thanks, appreciate it!

Mvg Peter Elderson

**Comment by pelderson** [comment]
This request is changed due to the fact that all elements of recreational node networks are tagged with network:type=node_network. rXn no longer signifies a node network. We still want special handling for node networks, but not based on the r in rXn. And not country-specific, but general, based on the tag.
Status update, see https://github.com/waymarkedtrails/waymarked-trails-site/issues/322#issuecomment-531165955

**Comment by lonvia** [comment]
Closing in favour of #322.
