### ISSUE TITLE
support semicolon separated lists in the network tag

### ISSUE THREAD

**Issue by Hufkratzer** [waymarkedtrails/waymarked-trails-site#321]
WT supports semicolon separated lists in the route tag (see https://github.com/waymarkedtrails/waymarked-trails-site/issues/186). But then it should also support semicolon separated lists in the network tag because the different routes can belong to different networks. Currently a route with network=ncn;nhn;nwn isn't recongnized as national route, see
https://hiking.waymarkedtrails.org/#route?id=50288
https://mtb.waymarkedtrails.org/#route?id=50288
https://riding.waymarkedtrails.org/#route?id=50288

**Comment by lonvia** [comment]
The change is live but I haven't reindexed the affected routes. They will sort themselves out with time.
