### ISSUE TITLE
support route=* + <access tag>=yes (?)

### ISSUE THREAD

**Issue by Hufkratzer** [waymarkedtrails/waymarked-trails-site#323]
Some mappers didn't tag multiaccess routes with a semicolon-separated list  but with route=* + \<additional access tag\>=yes instead, 2 examples with foot=yes + bicycle=yes + horse=yes:
https://www.openstreetmap.org/relation/916331
https://www.openstreetmap.org/relation/2804113
They can only be found in the WT maps corresponding to what is in the route=* tag but not in the others. Shouldn't they?

We have
2461 rel. route=* + foot=yes (2 % of 114832 rel. route=hiking)
1583 rel. route=* + bicycle=yes (2 % of  69890 rel. route=bicycle)
  363 rel. route=* + mtb=yes (4 % of  8216 rel. route=mtb)
  113 rel. route=* + horse=yes (7 % of  1552 rel. route=horse)

Related:
* https://github.com/waymarkedtrails/waymarked-trails-site/issues/186
* https://github.com/waymarkedtrails/waymarked-trails-site/issues/321

**Comment by lonvia** [comment]
I'm really not a fan of adding another tagging schema for this. Looking a bit closer at the numbers:

* foot=yes: 123 route=bicycle, 23 route=mtb, 7 route=horse
* bicycle=yes: 184 route=hiking, 120 route=foot, 2 route=horse
* mtb=yes: 305 route=hiking, 39 route=bicycle (really?), 4 route=horse
* horse=yes: 71 route=hiking, 19 route=bicycle, 3 route=mtb

The missing ones are either on routes of the same type or on public transport routes. So we are more in the less than 1% region here.

**Comment by lonvia** [comment]
Let's leave it at the semicolon version.
