### ISSUE TITLE
cycling map shows non-bicycle routes

### ISSUE THREAD

**Issue by Nzara** [waymarkedtrails/waymarked-trails-site#324]
The cycling map shows also some route currently map not as bicycle route. 
See relation 5341855 for example

**Comment by lonvia** [comment]
To clarify: the `route=bicycle` tag has been removed from the relation a day ago but the route is still visible in the map.

**Comment by Nzara** [comment]
An other example is:
1. select superroute 9727518
2. select select part 3 of superroute "Drauradweg"
3. show on map

==> route 47953 is shown from Dravograd to Möllbrücke 
- route=bicycle, 
- **no** members 
- last modified: July, 5

**Comment by lonvia** [comment]
The fix is live but I haven't removed the existing spurious relations from the database yet. Needs some consideration how to do it.

**Comment by lonvia** [comment]
I've cleaned out the hiking, cycling and MTB views now.

The second example turns out to be a different problem.
