### ISSUE TITLE
cached route level/label information

### ISSUE THREAD

**Issue by richlv** [waymarkedtrails/waymarked-trails-site#325]
While drawing in the missing sections of the E9 hiking route, noticed that the route is generally displayed with blue labels, but some sections have white labels.

This seems to be related to the nested relation status - the daily routes are nested in the "master" relation for the whole E9. If a daily route is not included in the master relation, it gets white labels. If it is included, it gets blue labels.

But the weird thing is that some sections are correctly included in the master relation, while they still get the white labels. From my experience in the Latvian stretch, this happens when a section is initially not included in the master relation.
Adding it later still preserves the white labels (zooming in actually alternates between blue/white labels depending on zoom level and region). It's almost as if something has been cached regarding the relation status or label information.

Several sections in Estonia and Latvia have this problem - I checked one of the Estonian ones, and it is also included in the master relation:

![Screenshot 2019-09-16 at 14 56 53](https://user-images.githubusercontent.com/112888/64956173-a8c7c500-d892-11e9-95dc-4a42cc4b4b9f.png)

The region where this can be observed: https://hiking.waymarkedtrails.org/#?map=8!58.2025!23.7159 .

**Comment by lonvia** [comment]
I can confirm that relation remains a 'top route' when it is added to a parent. I'm not entirely sure how to fix this though without making the update process very heavy. It does fix itself next time the relation itself is touched.

**Comment by richlv** [comment]
> It does fix itself next time the relation itself is touched.

Here we have 3 level relations - whole E9, country level, and daily level.
Would modifying the daily level or country level route get this fixed?

**Comment by lonvia** [comment]
> Would modifying the daily level or country level route get this fixed?

Yes but, please: don't. It's really not more than a visual glitch and you shouldn't artificially add versions to relations to work around a bug in the renderer. (What you could do is fix the `name` tags. That's a really bad abuse of the tag. Same goes for `description`. Neither is anything human readable.)

**Comment by richlv** [comment]
Well, tagging (or touching) for the renderer is discouraged, but the desire is strong, especially when looking for publicity screenshots :)

As for the name/description, I followed the practice on the existing sections in Latvia and Estonia. Will see about coordinating with other mappers to improve this in a consistent manner.

**Comment by lonvia** [comment]
Should be fixed with https://github.com/waymarkedtrails/waymarkedtrails-backend/commit/13f8e4ec675102e2b34a93b8cb60f1416e45987b

When updating the code for an existing database, be aware of the DB migration mentioned in the commit message.

**Comment by richlv** [comment]
Thank you so much for the fix :)
