### ISSUE TITLE
Bad Cisco WBRS (Site Score): Site blocked on many corporate networks

### ISSUE THREAD

**Issue by DonHansDampf** [waymarkedtrails/waymarked-trails-site#328]
Hello,
the site itself has a bad WBRS (Cisco's Site Threat Scoring System) which results in a blocked site on most corporate networks (waymarked receives a score of -8.1, most networks block sites below -6). 

>  WBRS: -8.1, WBRS Threat: phishing, WBRS Threat Reason: Hosted on IP controlled by a group or individual known to be malicious. Identified as a phishing or spam-related site.

Dunno if you can do anything about it, or if it is even a false alarm. But I haven't found any other issues with this topic, and maybe you want to change that (as i know you can even contact cisco as the site owner and request an update of this score).

Greetings

**Comment by lonvia** [comment]
The server is hosted at Hetzner. If Cisco has a block on Hetzner IPs in general, there is very little I can do about that.

**Comment by DonHansDampf** [comment]
I am no Cisco Expert and I already though something 'stupid' is the reason for this score ;) A contact of my company told me, that only a small subnet of hetzner's IPs got a bad score (or it seems like that).

Like i said, just wanted to let you know. Maybe you want to get in touch with Cisco, maybe you want to ignore that fact. Dunno. :)
