### ISSUE TITLE
Elevation profile does not work anymore

### ISSUE THREAD

**Issue by robhubi** [waymarkedtrails/waymarked-trails-site#329]
Tested with Firefox and IE on win7 64bit.
Error Message:
<div class="elevation-content elevation-error" style="display: none;">Es wurden keine Höhendaten gefunden.</div>

**Comment by pelderson** [comment]
+1. It does not look like a data issue.

**Comment by lonvia** [comment]
Fixed now.

**Comment by pelderson** [comment]
thnx for the quick fix!

**Comment by robhubi** [comment]
Dankeschön
