### ISSUE TITLE
Node network routes of skating networks not shown anymore

### ISSUE THREAD

**Issue by A67-A67** [waymarkedtrails/waymarked-trails-site#330]
Thanks for the new rendering of node networks. It looks really good!

Although the routes of the skating networks are not shown anymore. Only the numbered nodes are shown. See [here](https://skating.waymarkedtrails.org/#?map=14!51.9597!4.309). Expected would be a similar rendering as for cycling and hiking node networks.

These routes are tagged with:
- route=inline_skates
- network:type=node_network
- (network=rin)

**Comment by lonvia** [comment]
Should be there now.
