### ISSUE TITLE
Node-network lines disappear when part of a longer rwn route

### ISSUE THREAD

**Issue by pelderson** [waymarkedtrails/waymarked-trails-site#332]
Walking node routes can be lwn, rwn, nwn or iwn. Currently almost all node2node routes are rwn. At the same time, there are regional hikes entirely composed of node2node routes. Because of the hierarchical display method (if same network tag then do not display the sections), the sections will not be rendered. So the node2node route lines disappear from the node network when they are also part of an rwn route.
Could the hierarchy mechanism be adapted to take the network:type=node_network tag into account? 
 
Example: https://hiking.waymarkedtrails.org/#route?id=9576945 Zuiderwaterliniepad. This regional  route is developed and waymarked using the node network system.

**Comment by pelderson** [comment]
Is there any chance of this problem getting fixed in the foreseeable future? If not, please tell me, because then I have to redo a few regional route relations with ways instead of using the existing node2node relations as parts.

**Comment by lonvia** [comment]
Yes, the node networks should never be considered sections. I'll look into that.

**Comment by lonvia** [comment]
Implemented in 9b2ee8aede26493ded846dd22736db32121c4e85. I screwed up updating the database, so this change will apply itself only gradually. I did update the Zuiderwaterliniepad, though.

**Comment by pelderson** [comment]
Great! I'm very happy with the result!
