### ISSUE TITLE
Use from and to tags in route list

### ISSUE THREAD

**Issue by pelderson** [waymarkedtrails/waymarked-trails-site#333]
For hiking routes, the name tag is currently (ab)used to show from where to where the section goes, and to get an ordered display of the sections of a long route. It's massive tagging for the renderer, I'm afraid. If the from and to tags were used in the section list in addition to the name, this abuse could be greatly reduced without losing the information on waymarkedtrails. 

How about using "_name_ _from_-_to_" as the displayed name in the section list? If there is no name, you just get _from_-_to_. If the section name is the same as the parent route, you get _routename_ _from_-_to_. If nothing changes, most hiking routes will display as it is now, except the ones which have both from and to AND also a name including the from and to redundantly.

The ordering of the sections is now alphabetically by displayed name. I think this should be: in order in which they appear in the parent route relation. If the parent relation is badly ordered, this should be fixed in the mapping, which is a fairly easy thing to do even in Id and Potlatch. (This also applies to the hight profile and the gpx export).

This issue aims at returning to intended use of existing and documented tags. Nothing new, so no new proposals and discussions of tagging are needed. How to get mappers to retag a sh1tload of relations is another thing... Since I do regular consistency checks on almost all long walking routes in The Netherlands, I think for The Netherlands I can get it done fairly quickly as soon as this request is (hopefully) approved!

**Comment by pelderson** [comment]
This is great news, I was really waiting for this. I have adapted a route with 20 sections, see https://hiking.waymarkedtrails.org/#route?id=2552826
After looking at the results I have some questions about the sections list display.

- I noticed when the sections have no name tag but do have a symbol tag, the symbol tag (free text) is shown first. This doesn't seem logical to me!

- To the right, I see the ref. Is that the ref tag value of the section or the ref tag value of the parent route? Because usually they are the same for the parent and all the sections.

- Without the symbol tag, de sections list displays the section's ref tag again. So the whole sections list is a table of refs, all the sections show up the same! If I select one of the sections, it shows up with a "name" composed of from - via - to (I seldom have via's so did not test that). https://hiking.waymarkedtrails.org/#route?id=8614819
I would expect the sections list to show the same information as the section detail display. Is my tagging wrong?

- Ideally, in my mind, the sections in the section list would display: the name followed by the section_ref and the from-via-to display name, e.g. Grote Rivierenpad - 02 - Maasland - Geervliet.  If there is no name tag, then ref takes its place: LAW 6 - 02 - Maasland - Geervliet

I think taking semicolon as the separator for multiple via values does not need a vote; how about I discuss it on the tagging list with a "live" example, then add it to the wiki page of the via key? I don't see any alternative coming up. How it's dosplayed is another matter, that's not for the taggers to decide. 

This issue did not address the use of the existing key section_ref for this purpose. I could discuss that on the tagging list as well.

**Comment by lonvia** [comment]
I forgot the itinerary info for sub/super-sections. That should work now.

I'm not aware that we got aware that we got anywhere with section_ref, section_name etc. It's certainly documented anywhere. In any case, it should get it's own issue.

**Comment by pelderson** [comment]
That's great, it works! I can take the itinerary out of the name now. I
have done this in https://hiking.waymarkedtrails.org/#route?id=2552826 , it
looks much better!

Currently, the parent name and the section_ref are still in the name tag.
If I leave this out, the sections are alphabetically ordered according to
the itinerary, which is not the correct order. So I have to force ordering
through the name tag.

Also, when displaying the section details, the parent route name is not
apparent unless I put it in the section's name tag. So that's what I do for
the moment. In JOSM similar things happen when there is no name tag in the
section relations, which makes maintenance more difficult and time
consuming.

Best, Peter Elderson


Op ma 24 aug. 2020 om 20:53 schreef Sarah Hoffmann <notifications@github.com

**Comment by lonvia** [comment]
section_ref/name and order are different issues. The first needs to go through the tagging@ list first. Feel free to open a new issue for the second. Closing this one, as to/from/via seems to work correctly now.
