### ISSUE TITLE
Shelters and huts

### ISSUE THREAD

**Issue by pangoSE** [waymarkedtrails/waymarked-trails-site#341]
Hi
I suggest we add more information about the shelters and huts. When planning a hike it is really nice to know the details of the sites you are hiking to.

Right now there is no "more information about this feature" style picker which means I have to go to osm.org via the link and do the picking there. That I can do but it is very hard to explain to newbies and people who just wanna go on a hike. 

I started collecting photos of shelters and adding them with image=url, could these be rendered on mouse click in a JS-popup (see picture) or in a sidebar together with the node information? (this would be really nice, because there is no map currently both showing routes and shelters with images and information easily available)

How much work would it be to implement this?
Naturkartan.se implemented something like this, see example here https://naturkartan.se/sv/vasterbotten/vindelvaggileden
![popup-shelter](https://user-images.githubusercontent.com/11300782/72207419-45911c80-3499-11ea-9215-fbe429fc29b1.png)

**Comment by pangoSE** [comment]
This is how google choose to do it on My Maps, which is simpler and works quite good.
![popup-google](https://user-images.githubusercontent.com/11300782/72207501-29da4600-349a-11ea-8327-23943d7af06f.png)

**Comment by lonvia** [comment]
It would be nice to have more info about hiking-related POIs on the map but realistically speaking, I don't see I ever get around to doing it. There already is the generic ticket #18 tracking this, so I'm closing it here.

**Comment by brotkiste** [comment]
You can use overpass (e.g. https://github.com/kartenkarsten/leaflet-layer-overpass ) for that
