### ISSUE TITLE
Feature Request: Rendering of ref:colour* on cycle routes

### ISSUE THREAD

**Issue by McLondon** [waymarkedtrails/waymarked-trails-site#342]
I have some of the cycle routes in London (e.g. [C6](https://cycling.waymarkedtrails.org/#route?id=7870680) and [NCN 4](https://cycling.waymarkedtrails.org/#route?id=1318931&map=14!51.5016!-0.0938)) tagged with "*ref:colour*" + "*ref:colour_bg*" + "*ref:colour_tx*". This tagging is documented at https://wiki.openstreetmap.org/wiki/Key:ref:colour.

To somewhat replicate the **hiking** map rendering of "*osmc:symbol*", would it be possible for  for the **cycle** map to use this 'ref colour' tagging to render the ref as a coloured 'symbol'?

**Comment by lonvia** [comment]
Sorry, but I actually consider it a feature that the cycle map is not cluttered with shields in all kinds of colors (often in background/foreground color combinations that are close to unreadable). The cycle map already supports the color tag. For anything that goes beyond that, you'd have to show that it adds vital information to the map, that is not yet available with the current rendering.
