### ISSUE TITLE
How to deal with ref which is longer that 5 characters and cannot fit to label?

### ISSUE THREAD

**Issue by pedjas** [waymarkedtrails/waymarked-trails-site#344]
We have bicycle routes marked using ref that is longer than what can fit into route label on map.

What is your recommendation how to deal with it? We obvously cannot shorten route identification in ref key as those are official identification. We could shorten them in some alternative key if that is possible to be used.

Or, can label be redesigned to fit ref content length?

**Comment by lonvia** [comment]
It is not possible to show refs longer than 5 characters, they will be shortened to fit. There simply is no way to make room on an automatically generated map for such long labels.

Do you have an example relation with such a long ref?

**Comment by pedjas** [comment]
In Serbia official bicycle and hiking trails have longer identification.

Here you may see some of the biking routes. There is an option to show Waymarked Trails on the map.

Thing is, when you look at trails at national level, if you want to be organized they cannot be identified in five characters, especially with regional and local trails in the system.

Possible solution could be to introduce short-ref tag which could contain alternative identificator that is usable on local level and that may be short.

Besides that, I see no reason limitation in displaying longer refs. That limitation is introduced by graphical designer.

**Comment by lonvia** [comment]
A link would have been helpful. I have found it in the meantime. The answer is still the same. There is no way to get this cartographically on the map without changing the entire design. So I'm closing this as won't fix.
