### ISSUE TITLE
No RCN network in Netherlands

### ISSUE THREAD

**Issue by pgavrilov** [waymarkedtrails/waymarked-trails-site#345]
Why regional RCN network disappeared in Netherlands? Outside it's border all is staying as one year ago:

Border of Netherlands and Germany 2020-03:
![Border of Netherlands and Germany 2020-03](https://user-images.githubusercontent.com/3817702/77762136-1b87d900-704a-11ea-8678-a5e0117aa250.jpg)

Same place 2019-04:
![Same place april 2019](https://user-images.githubusercontent.com/3817702/77762424-90f3a980-704a-11ea-8a1b-b52c748d5369.jpg)

Netherlanders has changed their tagging system?

**Comment by lonvia** [comment]
See #322.
