### ISSUE TITLE
Local Cyclepaths / Networks not visible in the cycling map

### ISSUE THREAD

**Issue by lumica89** [waymarkedtrails/waymarked-trails-site#349]
When I tag paths/ streets with local cycling routes which are basically no routes in terms of OSM terminology by using network = lcn or lcn=yes directly on the appropriate lines, this has no visibility on the cycling map of waymarkedtrails. According to https://wiki.openstreetmap.org/wiki/DE:Key:network everything seems to be correct in terms of tagging and standards. Could you please make those elements visible in the cycling map, because this is very useful for cyclists and fits to the public radrouten-planning maps.

![2020-04-29_21h30_26](https://user-images.githubusercontent.com/14803373/80638911-80778a00-8a61-11ea-9d3e-c235bc2953c2.png)

Example could be seen here:
https://cycling.waymarkedtrails.org/#?map=17!50.9419!11.7462

Thanks for your answer!
Martin

**Comment by lonvia** [comment]
The map only shows cycle _routes_, i.e. Routes that are mapped as relations. It does not inspect tags on the `highway` ways. This kind of tagging is deprecated. If you want to tag cycle networks , have a look at the [network:type](https://wiki.openstreetmap.org/wiki/Key:network:type) key.

**Comment by lumica89** [comment]
Hi lonvia, 
is there any reference regarding the deprecated way of tagging? I'm wondering since this way is still described in the German wiki regarding mapping of bycicle lanes: https://wiki.openstreetmap.org/wiki/DE:Fahrradroutentagging#Welche_Routen_sollen_erfasst_werden.3F and here: https://wiki.openstreetmap.org/wiki/User:JochenB/DE:bicycle/Fahrradnetze_kartieren

**Comment by lonvia** [comment]
I see. The kind of networks that Jochen describes are distinctly different from the bike routes that waymarkedtrails aims to show. They are out of scope here. Personally, I'd rather put them in the same category as destination signage for cars but I guess that's a matter of taste.
