### ISSUE TITLE
"markers" for local routes on zoom level <11

### ISSUE THREAD

**Issue by ypcyc** [waymarkedtrails/waymarked-trails-site#352]
Is it possible to add feature to show "markers" for local routes on zoom level <11?

**Comment by lonvia** [comment]
No, sorry that is not possible because there are areas which are very dense. At the moment it is not possible to have different rendering per area according to the density.

**Comment by ypcyc** [comment]
Why "clustering" can't be used for such cases?
https://openlayers.org/en/latest/examples/cluster.html?q=overlay

**Comment by lonvia** [comment]
I'm closing this here as this is not going to happen on a generic global scale. Any solution must be based on the density of hiking routes in an area.

**Comment by Talkless** [comment]
@lonvia And why clustering is not a solution here?

**Comment by lonvia** [comment]
Because we are talking about bitmap maps, so clustering would have to happen on a completely different level. Even if we had vector maps, simple OL vector clustering is ugly. So that clearly will not happen. There is no quick-fix solution to the whole low-level zoom mess.

**Comment by Talkless** [comment]
> Because we are talking about bitmap maps, so clustering would have to happen on a completely different level

I imaging under <11 level, LWN's are not rendered on the bitmap, but JavaScript managed clustering icons appears. I guess they do not have to be THE symbols of the routes, just hint use that there are some routes that you can see if zoomed in.
