### ISSUE TITLE
Waymarked trails/routes offline

### ISSUE THREAD

**Issue by Aluhut** [waymarkedtrails/waymarked-trails-site#355]
Hi there,

im searching for a way to use the function of your site offline in QMapShack.
As I saw, could I download .gpx files for every single way but im trying to get them all or at least for a specific area. I didn't find out how you generate that files or what the source is. 
Can you please give me a hint where/how to get that file/-s?

**Comment by lonvia** [comment]
The routes are not available for bulk download. The original data comes from OpenStreetMap. You can download dumps from OpenStreetMap and process the data yourself. You can try out the new [backend project](https://github.com/waymarkedtrails/waymarkedtrails-backend) which limits itself to the bare necessities for the data processing.  However, be aware that I can only give very limited support for custom setups. This stuff is really mostly here for driving the website.
