### ISSUE TITLE
Some guideposts are invisible but still clickable

### ISSUE THREAD

**Issue by amadvance** [waymarkedtrails/waymarked-trails-site#361]
Some guideposts are not shown even if they are present as you can show their information, and even click them if you know where to click.

This seems independent of the guidepost attributes as I have many others that are shown correctly. I tried many browsers and devices, but it's always the same.

This is an example of what is shown after clicking on the invisible guidepost. You see that inside the small circle there is no guidepost. 

![missing_guidepost](https://user-images.githubusercontent.com/747159/89263589-d300ad80-d631-11ea-890f-f4c47c73349e.png)

This is the url of the guidepost: https://hiking.waymarkedtrails.org/#guidepost?id=7549614386&map=18!45.7944!9.5782

I tried to make some changes at the "destination" text and position, but they remain invisible. This really looks like a mystery to me :)

These are others invisible guideposts I found. They are nearby and in sequence, but no idea if this matter. 

https://hiking.waymarkedtrails.org/#guidepost?id=7731914692
https://hiking.waymarkedtrails.org/#guidepost?id=7731914693
https://hiking.waymarkedtrails.org/#guidepost?id=7731914694
https://hiking.waymarkedtrails.org/#guidepost?id=7731914695
https://hiking.waymarkedtrails.org/#guidepost?id=7731914696
https://hiking.waymarkedtrails.org/#guidepost?id=7731914697
https://hiking.waymarkedtrails.org/#guidepost?id=7731914698
https://hiking.waymarkedtrails.org/#guidepost?id=7731914699
https://hiking.waymarkedtrails.org/#guidepost?id=7731914700

https://hiking.waymarkedtrails.org/#guidepost?id=7549614386
https://hiking.waymarkedtrails.org/#guidepost?id=7549614387

Thanks in advance!

**Comment by lonvia** [comment]
Guideposts are only rendered when they appear near a route. (Or, more technically correct: they only get rendered when there is a route on the level 9 tile they appear on.) This is a bit of an optimization on the server side.

**Comment by lonvia** [comment]
I've reenabled "guidepost-only tiles" but won't recreate the tile database, so this issue will only fix itself in time while updates are applied.

**Comment by amadvance** [comment]
Just to report that now al guideposts are visible. It took some time to get the update, but it was worth waiting!

Thanks!
