### ISSUE TITLE
Routing overlay is no longer updated

### ISSUE THREAD

**Issue by robhubi** [waymarkedtrails/waymarked-trails-site#363]
The last update was more than 2 days ago on 03.Sept.2020 13:11:02

**Comment by lonvia** [comment]
Yes, I'm on it. The disk was out of space. A new server is already in the works. Should be ready in a day or two.

**Comment by lonvia** [comment]
New server is now live. It is still in the process of catching up. It should be done by tomorrow morning.

**Comment by robhubi** [comment]
It works again. Thank you very much for your efforts.
