### ISSUE TITLE
SLOPES map: piste profile and GPX/KML files download is not working 

### ISSUE THREAD

**Issue by Nikolai79** [waymarkedtrails/waymarked-trails-site#367]
Some problems on the piste details (Winter sports map):

Although way ID is been shown and piste distance and OSM tags are also been displayed some of the features have a problem:

a)
Piste profile is not been displayed

b)
When trying GPX and KML file download the browser is giving this error:
ERR_INVALID_RESPONSE

These three features seen to be working normally in the other Waymarked maps.

**Comment by lonvia** [comment]
I think that is fixed now. If not, please provide examples.

**Comment by Nikolai79** [comment]
Hi again,

There are still some problems :-(

I have tried several ski pistes and several ski resorts and they have all the same issues described before. Despide your troubleshooting the piste profile and the GPX/KML download features are not working.
I have reproduced the problem in different systems and browsers (Linux Mint and Windows 10 and Firefox, Chrome and Edge). Also with a mobile running Android and Chrome browser (same result).

- All browsers don´t show anything when clicking on the Altitude profile option. The arrow moves down and nothing happens. 

- With the GPX/KML download Firefox does nothing at all and the other browsers show the error: ERR_INVALID_RESPONSE

Here you have some examples:

One ski piste:
https://slopes.waymarkedtrails.org/#route?id=221200754&type=way

Link to the GPX download:
https://slopes.waymarkedtrails.org/api/details/way/221200754/gpx

Link to the KML download:
https://slopes.waymarkedtrails.org/api/details/way/221200754/kml


More examples (pistes):

https://slopes.waymarkedtrails.org/#route?id=258666875&type=way&map=18!45.866!6.4107
https://slopes.waymarkedtrails.org/#route?id=117012121&type=way&map=16!46.7914!9.8344
https://slopes.waymarkedtrails.org/#route?id=261265396&type=way&map=17.114267462509716!63.4039!13.1063
https://slopes.waymarkedtrails.org/#route?id=261367416&type=way&map=18!59.7286!10.1616
https://slopes.waymarkedtrails.org/#route?id=190568975&type=wayset&map=18!39.6072!-106.3349

And some download errors examples:
https://slopes.waymarkedtrails.org/api/details/wayset/190568975/gpx
https://slopes.waymarkedtrails.org/api/details/wayset/190568975/kml
https://slopes.waymarkedtrails.org/api/details/way/470098257/gpx
https://slopes.waymarkedtrails.org/api/details/way/470098257/kml


Some time ago I am pretty sure both profile display and downloads option were both working. I can´t precise when the problem started :-(

It is really a shame. I am publishing a review of ski maps talking about different tools options and Waymarkedtrails has some unique features but they are not working. 
Thanks for your trying and for try to fix the issues. I promise to update the article as soon as the features are working again.
:-)

**Comment by lonvia** [comment]
KML and GPX should be fixed now. So are the elevation profiles for ways.

Elevation profiles for waysets are not implemented yet because they usually are not linear anyway, so that it is not clear what the elevation profile should look like.

**Comment by Nikolai79** [comment]
Hi again,

Yes they are working now!
The elevation profiles are running nicely as expected and now the gpx/kml download is also possible.
Thanks a lot. 

Merry Xmas
