### ISSUE TITLE
Font of map is broken

### ISSUE THREAD

**Issue by tankaru** [waymarkedtrails/waymarked-trails-site#368]
The font on the map is broken in East Asia.
("Routes" side panel font is displayed correctly.)
https://hiking.waymarkedtrails.org/#routelist?map=12.938164880189527!35.6788!139.7416

This issue has been reported in past issues (#234 for example) and should have been resolved. I remember fonts were fine a while ago. But has it recurred?

**Comment by lonvia** [comment]
I forgot to install a couple of fonts when switching machines. Should be fixed now.

**Comment by tankaru** [comment]
Thanks a lot! Now it works fine!
