### ISSUE TITLE
Missing expected copyright notice for 3rd party use

### ISSUE THREAD

**Issue by mikehaertl** [waymarkedtrails/waymarked-trails-site#369]
I'd like to [add the tile URLs](https://github.com/mikehaertl/leaflet-providers/commit/16f8f82c2e59c04ec5f2dcf9a23ab7a9ffaffa67) to the [leaflet-providers](https://github.com/leaflet-extras/leaflet-providers) plugin of the [leaflet](https://leafletjs.com/) map library.

I could not find a clear statement what the expected copyright note should include. I only found an example on  https://opentopomap.org/ where they have "**&copy; lonvia**". So I would add something like this:

```html
Trails:
&copy; <a href="http://waymarkedtrails.org">lonvia</a>
(<a href="https://creativecommons.org/licenses/by-sa/3.0/">CC-BY-SA</a>)
```

Is this sufficient?

**Comment by lonvia** [comment]
Please attribute to OpenStreetMap and waymarkedtrails.org. So similar to other layers you have:

`'Map data: {attribution.OpenStreetMap} | Map style: &copy; <a href="https://{hiking,cycling,...}.waymarkedtrails.org">waymarkedtrails.org</a> (<a href="https://creativecommons.org/licenses/by-sa/3.0/de/deed.en">CC-BY-SA</a>)'`

**Comment by mikehaertl** [comment]
@lonvia Thanks, I've updated the attributions accordingly (see here: https://github.com/mikehaertl/leaflet-providers/commit/f8326c1d8b38ca41ee908f38da8d79bd2f1fb91c)

But I found that it quickly gets quite lengthy and repetitive:

![attribution_wmt](https://user-images.githubusercontent.com/675062/98910583-adeac900-24c3-11eb-822f-3d5619e05ddd.png)

* Is attribution to OpenStreetMap really always required? If e.g. `OpenTopoMap` is used as base layer it already adds that notice. (On the other hand it would be missing if another provider is used that is not based on OSM.)
* Could you maybe live with only one generic link to `https://waymarkedtrails.org` for all types instead of the specific links for each variant (`hiking.waymarked...`)? This would prevent a lot of repetition if more than one variant (hiking, cycling, riding,...) is added.

BTW you can preview the current providers and how the attribution is composed for multiple layers here: http://leaflet-extras.github.io/leaflet-providers/preview/index.html

**Comment by lonvia** [comment]
Yes, the attribution to OSM should be there, but having it once would be enough. So, ideally you would have a way to deduplicate the 'Map data' part. And also you need of course attribute waymarkedtrails only once (in which case it might indeed be better to link to https://waymarkedtrails.org instead of the subdomains).

If space is sparse, you could shorten to: `&copy; <a href="https://{hiking,cycling,...}.waymarkedtrails.org">waymarkedtrails.org</a>/{attribution.OpenStreetMap}`

**Comment by mikehaertl** [comment]
Great, I've gone with the middle way now:

```
Map data: {attribution.OpenStreetMap} | 
Map style: &copy; <a href="https://waymarkedtrails.org">waymarkedtrails.org</a>
(<a href="https://creativecommons.org/licenses/by-sa/3.0/de/deed.en">CC-BY-SA</a>)
```
So full attribution to OSM and only one attribution to waymarkedtrails using the main domain for all variants. 

PR to the leaflet-providers plugin linked above. Thanks for your help.
