### ISSUE TITLE
Render MTB node networks

### ISSUE THREAD

**Issue by Karthoo** [waymarkedtrails/waymarked-trails-site#372]
Hey,
I have (probably) added the [first MTB node network](https://www.openstreetmap.org/relation/11985572), but unfortunately the network route segments are not rendered on mtb.waymarkedtrails.org. You can find them by clicking around on the map, but you can't see them. (for example see https://mtb.waymarkedtrails.org/#route?id=11985549&map=15!48.6025!8.093)

**Comment by lonvia** [comment]
The route relations show up now. Looks like you have added the nodes as standard guideposts, so no special nodes are shown. We'd need to define something along the lines of https://wiki.openstreetmap.org/wiki/Key:rcn_ref .

**Comment by lonvia** [comment]
I haven't rerendered the tiles, so until the next changes come in, you'll see the routes only on zoom level 15 and above.
