### ISSUE TITLE
error executing makedb.py

### ISSUE THREAD

**Issue by ypcyc** [waymarkedtrails/waymarked-trails-site#373]
I was trying to install waymarkedtrails using docker with no luck.
Then I launched Ubuntu and did follow the install instructions with only difference in replacing
postgresql-9.4 with 12

but I always get error when executing makedb.py script:

./makedb.py -j 4 -f [dump.pbf] db import

Unknown map type 'routes'.
Traceback (most recent call last):
  File "makedb.py", line 178, in <module>
    __import__(mapdb_pkg)
  File "/waymarkedtrails/db/routes_maptype.py", line 22, in <module>
    import osgende
  File "/usr/local/lib/python3.8/dist-packages/osgende/__init__.py", line 22, in <module>
    from .mapdb import MapDB
  File "/usr/local/lib/python3.8/dist-packages/osgende/mapdb.py", line 11, in <module>
    from osgende.osmdata import OsmSourceTables
  File "/usr/local/lib/python3.8/dist-packages/osgende/osmdata.py", line 9, in <module>
    from osgende.common.table import TableSource
  File "/usr/local/lib/python3.8/dist-packages/osgende/common/table.py", line 22, in <module>
    from sqlalchemy.dialects.postgresql import insert
ImportError: cannot import name 'insert' from 'sqlalchemy.dialects.postgresql' (/usr/local/lib/python3.8/dist-packages/sqlalchemy/dialects/postgresql/__init__.py)

**Comment by lonvia** [comment]
The repo with the docker image is severely outdated and I don't have the time to maintain it. I've archived the repository now.

There are no up-to-date installation instructions for the current version of this repository, I'm afraid. I'll readd proper instructions once I've switched to the new repos (waymarkedtrails-shields, waymarkedtrails-backend, waymarkedtrails-api etc.) but until then, you are a bit on your own, I'm afraid.

The error above looks like you are using an unsupported version of SQLAlchemy. The production server currently runs on Debian stable and uses most of the packages from there except for the following which are installed from pip: pycairo==1.18.1 CherryPy==18.1.0 falcon==2.0.0 So if you want to try this on your own, I suggest to start with a Debian stable docker image as base as well.

**Comment by ypcyc** [comment]
As I said, after sending too much time with docker not working,yesterday I installed fresh ubuntu ob virtualbox, but still get that errors!

**Comment by ypcyc** [comment]
Thanks again for the feedback, I did install SQLAlchemy 1.2.18 and other versions like you suggested.
Everything went fine, just nodestore file is 66Gb instead of 32Gb.

For WMT_CONFIG=hiking ./frontend.py command, I had to run "pip3 install python-slugify"

Got not errors, but after everything was executed, http://localhost:8080/ still returns nothing :(

**Comment by ypcyc** [comment]
@lonvia I think there is a problem with latest frontend.py version. I have used previous version from Oct 22, 2019 and I works fine!
I haven't worked with CherryPy ,but I think problems lies in
    cherrypy.engine.start()
    cherrypy.engine.block()
