### ISSUE TITLE
Nordic crosscountry Routes are not listed

### ISSUE THREAD

**Issue by ppete2** [waymarkedtrails/waymarked-trails-site#376]
I think part of issue #347 still unsolved. For example if you open map at https://slopes.waymarkedtrails.org/#?map=15!47.7254!14.3218 and click onto "Routes", none of the nordic routes are being listed.

The routes' detail sites are created, for example https://slopes.waymarkedtrails.org/#route?id=8020184&map=15!47.7273!14.3193 . So the problem for nordic routes is just the creation of the list of routes in the current map screen.

**Comment by ypcyc** [comment]
I found same issue in my area: route list is empty. @st-anton if you check the example link @ppete2  has provided it is "piste" there is completely no reference to your mentioned "hiking, cycling, moutain biking etc." From data view everything is tagged correctly piste itself is rendered on the map, but doesn't appear on the list!

Also there are some other strange "routes" that do appear on the list instead, like https://slopes.waymarkedtrails.org/#route?id=130569205&type=wayset   When I try to click on wayset, I'm forwarded to OSM error 404 page 
https://www.openstreetmap.org/wayset/130569205

Winter season is coming and I can see a lot of people in my region a willing to get good Nordic skiing piste map. Please help!

**Comment by ypcyc** [comment]
@lonvia Could you please have a look at this issue? Relations in Slopes are not displayed in the Routes list, instead only "ways" are displayed.

**Comment by lonvia** [comment]
This should work now, now that the new version is deployed. At least all examples provided work fine for me.

**Comment by ypcyc** [comment]
@lonvia Thank you! Works almost perfect except that routes are not highlighted on zoom levels 11+

**Comment by lonvia** [comment]
@ypcyc Try reloading the site. It the issue with the highlighting persists, please open a new issue and give more informatio about the browser you use.

Closing the issue of listing nordic crosscountry routes.

**Comment by ypcyc** [comment]
@lonvia When I initially reported issue about zoom "11+" it was not working only on 11 and 12 zooms.
Now it's not working only on 12, on 11 routes are shown.
