### ISSUE TITLE
Show piste:type=skitour

### ISSUE THREAD

**Issue by hungerburg** [waymarkedtrails/waymarked-trails-site#379]
Skitouring is booming. You stick climbing skins under the skiers and then hike up a mountain. Might be rendered like piste:hike, perhaps a little more decent? Must not be too bold and clearly different from downhill pistes, as sometimes, the skitour hike goes up on the border of those.

Looking forward to exploring new tours from waymarkedtrails :)

**Comment by lonvia** [comment]
Skitours are intentionally omitted because they usually break the OSM 'on the ground' rule in the sense that they are not waymarked or otherwise officially maintained. I have strong opinions that they do not belong into OSM because of that and consequently not into waymarkedtrails. Sorry.

**Comment by lonvia** [comment]
Alternative maps showing skitours:
* https://www.opensnowmap.org/ 
* https://xctrails.org/

**Comment by hungerburg** [comment]
Thank you for the quick reply; Yesterday I mapped three of them, that are officially maintained and waymarked and looked at waymarkedtrails for quality assurance, so I noticed.  This is becoming ever more popular, most resorts have some, to channel the masses. They are called "Pistentouren". Not exactly what I meant with exploring ;) Both alternate maps already show (parts, depending on zoom). Maybe I can come up with a mapping scheme…

**Comment by hungerburg** [comment]
There exists piste:grooming=classic - not defined for skitours in the wiki, but for hiking, perhaps as a clue?

**Comment by hungerburg** [comment]
Hello Lonvia, I tagged three classically groomed skitours in this site https://www.openstreetmap.org/way/539203035 - it also has a snowpark ( to do stunts) and a playground (for the youngest) - What do you think, is it worth documenting this grooming (Pistentour) in the OSM wiki? Nearly all the resorts around here have at least one of that kind.
