### ISSUE TITLE
[node networks] Render other nodes than just rXn_ref nodes

### ISSUE THREAD

**Issue by pelderson** [waymarkedtrails/waymarked-trails-site#382]
I would like WMT to render lwn_ref=* nodes for walking node networks at the local level. 

(Since the node networks tagging system supports node networks at all four geographic scope levels l, r, n and i, and all modes of transport, the issue is much bigger, but use cases now emerge for the local level of walking networks. I'll include a horse riding example though. 

Use case 1: The French are starting to map node networks for walking and hiking. They now have a pilot network near Toulouse, see https://hiking.waymarkedtrails.org/#?map=14!43.5113!1.47
They see it as a local network, but for this pilot they temporarily agreed to tag the routes as rwn, and the nodes as rwn_ref. 
I had the same comment for a pilot in Germany, where the mappers decided not to continue until all the issues have been amended.  

Use case 2: a local node network in the dunes in Nederland: https://hiking.waymarkedtrails.org/#routelist?map=16!52.1397!4.3583
(Note: it was first mapped as one discontinuous lwn route, for the moment this can be kept until the conversion to a node network is finished. )

Use case 3: In Nederland, node networks for horse riding and canooing are developed. These are typically local node networks, within one forest, park, or limited nature reserve. We tag those as regional networks now, but that is actually tagging for the renderer: other levels don't show up! Example: https://riding.waymarkedtrails.org/#routelist?map=13!52.097!5.4142

I guess a quick solution would be to treat all **n_ref nodes as equal to r*n_ref if the tag network:type=node_network is present. 
It would mean that the Dutvch dunes example would show a cluster of nodes covering that part of the map.  So it would be better if the local nodes showed up at a higher zoom level than the regional ones. Also, it would be nice if the outer ring of the nodes would reflect the geographica scope, e.g. purple for local, yellow for regional, blue for national (yes, coming up!) and red for international (can't see that happen any time soon, though).

**Comment by lonvia** [comment]
There is two problems here: 1) the whole network node tagging should never have made any reference to a regionality level to start with. 2) You might have overlapping node networks and therefore need to express affiliation, something that is not yet possible with the current scheme. I strongly disagree that either should be solved by adding even more misnamed variations of the `rwn_ref` tag. Please see previous iterations of this discussion for further information.
