### ISSUE TITLE
On very big screeen (4800x4000) map corners lot loading?

### ISSUE THREAD

**Issue by juhanjuku** [waymarkedtrails/waymarked-trails-site#383]
I have very big screen, 4800x4000pix and no matter how long I wait, only center part of map is loaded.
Same with OSM or OpenTopo map.
![screen](https://user-images.githubusercontent.com/12792066/110940807-282b3d00-8340-11eb-8a4f-3101b6640b23.png)

**Comment by lonvia** [comment]
That is going to be hard to reproduce. Couple of questions:

* What browser are you using? Have you tried with a different one?
* Could you please check if you see the same on a standard OpenLayers map? For example: https://openlayers.org/en/latest/examples/full-screen-source.html (click arrow control in the upper right corner to make map full screen).
* Do you see any network errors? (Open the developer console, usually F12 will do that, go to the network tab, reload your page and check if any downloads get reported as an error.)

**Comment by juhanjuku** [comment]
Thank you for quick reply.

I think, you can reproduce it. I don't have such big monitor, I use
Infinite Screen v1.72 to enlarge browser screen space.
My goal is to save high resolution screenshot for A1 printer.
I'm using Chrome and Win7.
When opening openstreetmap.org, there is no problem, all map loads quickly.
I don't see any network errors.

Or maybe you can suggest better solution how can I generate high resolution
jpg for big size printout of waymarkedtrails map?

**Comment by lonvia** [comment]
openstreetmap uses leaflet, which might not have issues. Definitely sounds like an OpenLayers problem.

To generate maps for printing try https://maposmatic.osm-baustelle.de/ It can do waymarkedtrails overlays.

**Comment by juhanjuku** [comment]
I got answer from OpenLayers:

https://hiking.waymarkedtrails.org/ is using OpenLayers version 6.3.1 and when used in combination with Infinite Screen you are probably seeing #11259 which was fixed in version 6.4.0

Have you any plans to update OpenLayers version to 6.4.0 ?

**Comment by lonvia** [comment]
OpenLayers 6.4 breaks touch events on old IPhones and I wasn't able to make the recommended polyfill workaround work with the bundled OL that we currently use. So the upgrade has to wait until waymarkedtrails switches to the new svelte-based interface. I can't say when I'll have time to finish that.

**Comment by lonvia** [comment]
We are running 6.5 now.

**Comment by juhanjuku** [comment]
Thank's, now it works good.
