### ISSUE TITLE
Display colour for route=mtb

### ISSUE THREAD

**Issue by Reedyn** [waymarkedtrails/waymarked-trails-site#387]
Route colors seem to only display for route=bicycle, route=foot and route=hiking.

It would be great if it would show up on route=mtb as well.

**Comment by lonvia** [comment]
This should work now but will only show up when a route is updated next.

**Comment by Reedyn** [comment]
Has this been reverted? None of the routes that previously showed colour are now not showing it. 

See this route for example [Waymarked Trails](https://mtb.waymarkedtrails.org/#route?id=12698395&type=relation)/[OpenStreetMap](https://www.openstreetmap.org/relation/12698395)

**Comment by lonvia** [comment]
It didn't get ported over to the new version. Fixed now. Unfortunately, it again means you have to wait for the next update on the relation to take affect.
