### ISSUE TITLE
NET::ERR_CERT_DATE_INVALID for riding.waymarkedtrails.org

### ISSUE THREAD

**Issue by Hufkratzer** [waymarkedtrails/waymarked-trails-site#388]
I currently have this error message when I try to view https://riding.waymarkedtrails.org/ : 
<img width="300" alt="waymarkedridingerror3" src="https://user-images.githubusercontent.com/5958184/121411877-60a0de00-c964-11eb-845c-5369c2395df3.png">

All the other maps (hiking, cycling, ...) work. A few days ago I did not have this problem.

**Comment by lonvia** [comment]
Fixed.
