### ISSUE TITLE
Documentation for installation of (frontend) Python dependencies

### ISSUE THREAD

**Issue by hiddewie** [waymarkedtrails/waymarked-trails-site#391]
I would like to make a pull request for the frontend of the waymarked trails site. To test it, I want to run the frontend.

However, there is no documentation on how to install the dependencies (or even what they are). There is no `requirements.txt` file. Is the frontend runnable with Python 3 or is Python 2 required?

I simply tried to start the frontend with `python3 frontend.py` which then fails with an import, which I then try to install.

The dependencies I tried to install so far:
```
pip3 install cherrypy
pip3 install sqlalchemy
pip3 install babel
pip3 install jinja2
pip3 install markdown
pip3 install webassets
pip3 install slugify
pip3 install geoalchemy2
pip3 install shapely
pip3 install osgende
```

However `pip3 install osgende` then fails with
```
ERROR: Could not find a version that satisfies the requirement osgende
ERROR: No matching distribution found for osgende
```

How should the frontend dependencies be installed?

**Comment by lonvia** [comment]
Installation instructions (possibly outdated) for this repo are available in https://github.com/waymarkedtrails/waymarked-trails-site/wiki/Installation

There won't be any additional ones as this repo is on the way of being replaced at some point in the future.

osgende is not available in pip and there are no plans to publish it there. You need to install it manually via setup.py.
