### ISSUE TITLE
superroute not displayed in full

### ISSUE THREAD

**Issue by matkoniecz** [waymarkedtrails/waymarked-trails-site#394]
https://cycling.waymarkedtrails.org/#route?id=3870197&map=7!51.721!19.5794 is displaying superroute partially only

Note that https://www.openstreetmap.org/relation/7343678 is not higlighted

note to self: if that link is bad or has no chance to be fixed - update https://pl.wikipedia.org/wiki/Wi%C5%9Blana_Trasa_Rowerowa external links section

hmm, it is not appearing at all in https://cycling.waymarkedtrails.org/#route?id=7343678&map=14!50.1536!20.5831 - maybe something is bad with that relation?

**Comment by McLondon** [comment]
As https://www.openstreetmap.org/relation/7343678 is tagged with 'state=proposed', it will be not get displayed.

**Comment by matkoniecz** [comment]
Thanks! I removed `state=proposed`  as nonexisting parts are not mapped (as it should happen)

**Comment by lonvia** [comment]
So this can be closed as "data issue"?

**Comment by matkoniecz** [comment]
Yes, I know see that it is rendered properly after database replicated OSM changes
