### ISSUE TITLE
Some images are missing in the Localised rendering section

### ISSUE THREAD

**Issue by debyos** [waymarkedtrails/waymarked-trails-site#395]
In the [description of the Swiss hiking path network](https://hiking.waymarkedtrails.org/help/rendering/hikinglocal?lang=en), some images in the text are missing. 
You might correct the underlying links in the HTML code:
![image](https://user-images.githubusercontent.com/26843901/133321664-291b8928-51d8-468d-af8a-c987c6e2c3e1.png)

**Comment by lonvia** [comment]
Please note that I've only fixed the original English source. For translations the change needs to go through translatewiki first.
