### ISSUE TITLE
Add support for fitness_trail

### ISSUE THREAD

**Issue by Nekzuris** [waymarkedtrails/waymarked-trails-site#396]
Fitness trail are currently not displayed, maybe they can be added to hiking or in their own category.

**Comment by lonvia** [comment]
Duplicate of #219.

**Comment by pyrog** [comment]
Fitness trails could be displayed on the hiking style for the moment.
See https://github.com/waymarkedtrails/waymarked-trails-site/issues/408#issuecomment-1012014995
