### ISSUE TITLE
Superroute relation issues

### ISSUE THREAD

**Issue by ypcyc** [waymarkedtrails/waymarked-trails-site#397]
When I add new major route to OSM, I usually add by sections (they typically are 15-25km long). 
When all sections are added, I merge them into Superroute relation.
Previously it took few days for https://hiking.waymarkedtrails.org/ to hide sections from route list and leave only Superroute , now it's more than a week and all sections are still displayed together with Superroute.

Here is my example:
https://hiking.waymarkedtrails.org/#routelist?map=10!56.9755!27.6056

**Comment by lonvia** [comment]
This is essentially the same issue as #325. Relations are not updated when they get added to a superrelation.

Closing as duplicate here.
