### ISSUE TITLE
Precision of length values

### ISSUE THREAD

**Issue by ppete2** [waymarkedtrails/waymarked-trails-site#403]
Routes with a length of <10 km are listed with a precision of 0.01m. For example: 8.12 km - OK!

But routes with >= 10 km are listed with just a precision of 1 km. For example https://hiking.waymarkedtrails.org/#route?id=1535989&type=relation&map=14.0/48.0488/13.9158 is listed with "11 km" and "12 km". Please increase precision of routes with a length between 10.0 km and 99.9 km to 0.1 km. It's a difference if a route is just 10.5 km or 11.4 km - both listed as "11 km" right now.

For routes >= 100 km we can stay with a precision of 1 km.

**Comment by lonvia** [comment]
I don't think more precision is a good idea for the simply reason that we don't have the data for it. Neither is the OSM data precise enough nor is the algorithm that is used to compute the length. For example, it completely ignores altitude.

**Comment by ppete2** [comment]
I think I can not completely follow your arguments: Why is WMT than using a precision of 10 (!) meters for distances <10 km and sudddenly changes to rough 1 km? OSM data is as precise as mappers are mapping its ways. For exaxmple for distances of 10-20km they are far more precise than 1 km for sure ;-)
And the last point: Distances and areas are usually  always horizontal distances/areas. In OSM as well as in professional survey. And even for hilly hiking routes the difference between its horizontal length and its 3D-length can be ignored since its values are nearly the same. The relevant OSM-values regarding elevation differences of routes are _ascent_ and _descent_.

**Comment by lonvia** [comment]
You are right, 10m precision is too much. I will fix that.

**Comment by Nekzuris** [comment]
I agree with @ppete2 about the >10km precision, the data in OSM is precise enough to show 0.1km, like almost every hiking map.
Altitude is completely negligible, 10km with 1000m elevation is equal to 10.05km in 3D, and if you really want to take that into account it's possible now.
