### ISSUE TITLE
Render Nordic Walking route

### ISSUE THREAD

**Issue by giubarba** [waymarkedtrails/waymarked-trails-site#408]
I have seen issues related to new views, described in other threads. I make this new request similar but different: it is possible to insert the visualization of the paths with follow?
type = route|
route = nordic_walking

[https://wiki.openstreetmap.org/wiki/Tag:route%3Dnordic_walking](url)

Thanks for a fantastic website
Giulio

**Comment by lonvia** [comment]
This was already requested in #219. Closing as duplicate.

**Comment by giubarba** [comment]
It is not exactly the same, I just intend to make these traces visible on the existing view as well, without having to create new views.

Thanks
