### ISSUE TITLE
Exclude "alternative" members in "Elevation profile"

### ISSUE THREAD

**Issue by ivanbranco** [waymarkedtrails/waymarked-trails-site#409]
As in the title, would be possible to exclude `alternative` members to the "Elevation profile" calculation and just keep the `main` members? As it is now, adding a relation with a role that is different from empty or `main` to a superroute relation creates a "broken" elevation profile.

**Comment by lonvia** [comment]
This is already covered in #356. Still looking for a free minute to do something about it....
