### ISSUE TITLE
French translation of piste:type=sleigh should be revised

### ISSUE THREAD

**Issue by lucgential** [waymarkedtrails/waymarked-trails-site#410]
French translation of _piste:type=sleigh_ (Sleigh piste) in Waymarked Trails is "Piste de luge" which is not correct. Correct translation should be "Piste de traîneau" (see https://wiki.openstreetmap.org/wiki/Key:piste:type for the description of _sleigh_ and _sled_ values).
<img width="386" alt="image" src="https://user-images.githubusercontent.com/46304787/151385332-efd722b5-94c8-40ce-b75d-39c1125424f1.png">

**Comment by lonvia** [comment]
The waymarkedtrails site is translated at [translate wiki](https://translatewiki.net/wiki/Translating:Waymarked_Trails). You need to fix the translation there.
