### ISSUE TITLE
Render avalanche transceiver training zone and checkpoints

### ISSUE THREAD

**Issue by letypequividelespoubelles** [waymarkedtrails/waymarked-trails-site#415]
A new tagging scheme has been approved for [avalanche transceiver training zone and checkpoints](https://wiki.openstreetmap.org/wiki/Key:avalanche_transceiver). Could you render it for the winter sport map ? Thanks !

I think this kind of [icon](https://icon-icons.com/fr/icone/nfc-le-signal-de-point-de-controle-nf/2522) is the best.

Thanks a lot !

**Comment by lonvia** [comment]
waymarkedtrails doesn't render any POI information, so this is out of scope for now.

Closing in favour of the POI catch-all issue #18.
