### ISSUE TITLE
Trails in Japan don't show up on route list

### ISSUE THREAD

**Issue by lizzyd710** [waymarkedtrails/waymarked-trails-site#420]
I added existing paths to a [hiking route](https://www.openstreetmap.org/relation/14345820) in Aso-Kuju National Park, but when I [view it on the hiking map](https://hiking.waymarkedtrails.org/#routelist?map=14.0/33.087/-228.7598), the route list is blank. I noticed this for some other national and regional trails in Japan that I could see from a lower zoom level as well. I also can't click the trail to pull up the route information.

**Comment by lonvia** [comment]
You went over the edge of the map. Try the following link: https://hiking.waymarkedtrails.org/#?map=14.0/33.0906/131.2504

**Comment by lonvia** [comment]
I thought that OpenLayers properly wraps when you go out of the map bounds but apparently not. I will have to fix that in the website code, so you won't notice anymore. I'm reopening this report and will close once I've fixed the site.

**Comment by lizzyd710** [comment]
Sounds good! I wasn't sure if that was a website thing or a me thing.

**Comment by lizzyd710** [comment]
Awesome! Thanks so much!
