### ISSUE TITLE
No updates for 3 days and a half

### ISSUE THREAD

**Issue by xallaume** [waymarkedtrails/waymarked-trails-site#423]
Hi, I was wondering if you had an idea about when updates will happen again ? Is there something one can help ?

**Comment by markongh** [comment]
I've noticed this issue too.  Thanks for opening this issue.

**Comment by sun-geo** [comment]
I confirm, on the upper area of the map:
( https://cycling.waymarkedtrails.org )
there is an information text _"Last update: 8/21/22 1:15 AM"_

**Comment by lonvia** [comment]
This has to wait until I'm back from travelling, sorry.

**Comment by lonvia** [comment]
Should be fixed with https://github.com/waymarkedtrails/waymarkedtrails-backend/commit/15252ca1c69e61b5daa1928f1b7d500dcb7238c1 At the current speed the site will be up-to-date again by tomorrow noon.

**Comment by sun-geo** [comment]
> At the current speed the site will be up-to-date again by tomorrow noon.

Thank you - it's up-to-date again.   :-)

**Comment by sun-geo** [comment]
It seems currently there is another hourly (instead of common minutely) delay of osm-data update, on the upper area of the map:
( https://cycling.waymarkedtrails.org/ )
there is an information text "Last update: 9/4/22 4:06 PM"
