### ISSUE TITLE
Waymarkedtrails does not show routes on the map anymore

### ISSUE THREAD

**Issue by Andreas2430** [waymarkedtrails/waymarked-trails-site#424]
When opening waymarkedtrails, no routes are displayed on the map anymore. Only when a route is selected from the routes window, it appears as a yellow overlay. Tested on Firefox, Chrome and Edge.

![capture_20220911_120841](https://user-images.githubusercontent.com/102322614/189522162-87dd9fde-c75d-4aec-aea3-fd5398c8d9d8.jpg)
![capture_20220911_120850](https://user-images.githubusercontent.com/102322614/189522168-a507ff27-3bf4-496b-b728-aab35fe4777c.jpg)
![capture_20220911_120855](https://user-images.githubusercontent.com/102322614/189522175-bb05162c-8a5c-4b30-808b-0567a6a9390d.jpg)

**Comment by chrismaert** [comment]
I saw the same, still not working
