### ISSUE TITLE
502 errors when loading the site, paths do not appear

### ISSUE THREAD

**Issue by domhurr** [waymarkedtrails/waymarked-trails-site#429]
e.g. GET to https://tile.waymarkedtrails.org/hiking/9/285/178.png fails with 502, etc.
Presumably these failed GET requests are for the path tiles which do not appear...

Issue appears on all version of the site (hiking/cycling/mtb/etc...).
![Screenshot 2022-12-18 16 05 20](https://user-images.githubusercontent.com/2151568/208302809-22ea47d5-0260-4e5a-a4b2-474affaaba5d.png)

**Comment by lonvia** [comment]
Fixed.
