### ISSUE TITLE
Trail disappeared

### ISSUE THREAD

**Issue by moretti66** [waymarkedtrails/waymarked-trails-site#430]
The Via della Lana e della Seta (VLS) trail is half disappeared. It start in Bologna and it should end in Prato but actually it ends in Vernio.
Please reupload the full track!

**Comment by lonvia** [comment]
It hasn't disappeared. It's just that nobody has come around adding it completely. The data from waymarkedtrails.org comes from the [OpenStreetMap project](https://openstreetmap.org).

Closing as data issue.
