### ISSUE TITLE
Use of osmc:symbol in mtb and bicycle routes

### ISSUE THREAD

**Issue by amadvance** [waymarkedtrails/waymarked-trails-site#432]
It seems that the "osmc:symbol" is only used for hiking routes, and not for MTB and bicycle routes. I wonder if there is a specific reason for this, and whether its use can be extended to those routes as well.

It is common to have routes that have both a hiking and cycling variant, and it would be great to be able to display them in the same way.

Thanks!

**Comment by lonvia** [comment]
Duplicate of #223.

If you have more specific examples than 'it is common', please add them there and I consider to reopen.

**Comment by amadvance** [comment]
Added examples in #223
