### ISSUE TITLE
Add new types of route (route=foot and route=fitness_trail)

### ISSUE THREAD

**Issue by sylvain-m** [waymarkedtrails/waymarked-trails-site#434]
Hello,
What would you think of adding a tab for new types of route such as [`route=foot`](https://wiki.openstreetmap.org/wiki/Tag%3Aroute%3Dfoot) and [`route=fitness_trail`](https://wiki.openstreetmap.org/wiki/Tag%3Aroute%3Dfitness_trail)
Or, to avoid creating a new tab/domain, add these route type to the hiking category?
These would deserve to be visible in your great interface! (bravo for everything!)
Thanks to you.
Sylvain M.

**Comment by lonvia** [comment]
`route=foot` is already shown on the hiking page. For `route=fitness_trail` see #219. The comment https://github.com/waymarkedtrails/waymarked-trails-site/issues/219#issuecomment-1016834044 still applies.

Closing as duplicate.
