### ISSUE TITLE
Symbol background shape is not respected - all are square

### ISSUE THREAD

**Issue by stefanb** [waymarkedtrails/waymarked-trails-site#435]
On the map the visual difference between `red:white:red_circle` and `red:red_round:white_dot` is minimal, both are drawn as squares, while the second one should be round: https://hiking.waymarkedtrails.org/#routelist?relations=2316762,14090041&map=16.0/46.3304/14.581
![telegram-cloud-photo-size-4-5900206727721238770-y](https://user-images.githubusercontent.com/319826/232306356-8326fbc8-6c0a-4d07-9687-e1d831296530.jpg)

Images of round shapes should have transparent edges to give appearance of the round symbol.

Either the containing square should be removed or its `fill-opacity` set to 0:
https://github.com/waymarkedtrails/waymarked-trails-site/blob/df0194b845c92e92cc0433779544c321f3425d0e/frontend/static/img/osmc/background/red_round.svg?short_path=ca91004#L4

This applies to all `frontend/static/img/osmc/background/*_round.svg` and similar non-square shapes.

**Comment by stefanb** [comment]
Could be related to `ctx.rectangle(0, 0, w, h)` in `render_background()`:
https://github.com/waymarkedtrails/waymarkedtrails-shields/blob/0eb5e50291837c787fff1c0d4a916b5798e92e24/wmt_shields/common/shield_maker.py#L134-L140

**Comment by lonvia** [comment]
This is intentional. The outer background is there to be a visual connection between the line color and the shield. We could make the outer background transparent for red_round background but the visual difference would be minimal and it looks a bit odd. If anything, I'd rather change the form of the outline but would need to check if having different shapes doesn't become too distracting.

What is the difference between the two shields in the real world?

**Comment by stefanb** [comment]
>What is the difference between the two shields in the real world?

I am not aware of any with rectangular white background existing in the wild. The only one existing is the round blaze mark by mr Alojz Knafelc, aka "Knafelčeva markacija" - https://sl.wikipedia.org/wiki/Markacija :
![image](https://github.com/waymarkedtrails/waymarked-trails-site/assets/319826/577bc1db-2d20-4931-92bc-6949afbac2e8)
which is predominantly used in Slovenia.

For the context in OSM see: https://wiki.openstreetmap.org/wiki/File:Knafel%C4%8Deva_markacija.jpg

I suspect the reason for mappers often using the wrong one is because there is no significant difference in rendering of "white square with red circle" (`red:white:red_circle`) and "red circle with white dot" (`red:red_round:white_dot`) even though only the latter correctly describes it: 
![image](https://github.com/waymarkedtrails/waymarked-trails-site/assets/319826/bbd60c2f-b169-4bbf-8177-dabd8245f12c)

**Comment by lonvia** [comment]
Well, I assumed that the two routes in your example have different trail blazings. So I'd like to know what the trail blazings for these two routes look like that it is necessary to differentiate them.

**Comment by lonvia** [comment]
Closing as the reporter provided no further information.

**Comment by stefanb** [comment]
Uhm, @lonvia, what kind of further input were you expecting?

There was a discussion going on in the OSM forums: https://community.openstreetmap.org/t/osmc-simbol-za-knafelcevo-markacijo/110058 (in Slovenian language), with a [clear vote results](https://community.openstreetmap.org/t/osmc-simbol-za-knafelcevo-markacijo/110058/14) for `red:red_round:white_dot`:
<img width="701" alt="image" src="https://github.com/waymarkedtrails/waymarked-trails-site/assets/319826/bba16631-ebfc-49b1-a72c-8cc83cf985d5">
allowing us to unify our mapping.

Yet the rendering should not be in a strongly visible square.

**Comment by lonvia** [comment]
I wanted pictures of the marker used in nature for the route using `red:white:red_circle` and `red:red_round:white_dot` respectively. Rereading, it seems there are no different markers, you just can't make up your mind for the one existing marker which osmc:symbol to use..

**Comment by stefanb** [comment]
Indeed, there is more than one way to tag similar marks, but the chosen one red_round is not rendered correctly as round, but as a square with a circle in it.
