### ISSUE TITLE
Ways that are not highway=* should not be rendered as trail.

### ISSUE THREAD

**Issue by sebicodes** [waymarkedtrails/waymarked-trails-site#438]
I just stumbled over the rendering of the Auronzohütte (https://www.openstreetmap.org/way/186519265) as part of the hiking route 105 https://hiking.waymarkedtrails.org/#route?id=1067603&map=18.0/46.6122/12.2967, that is (like other alpine huts) rendered as a part of the route including the symbols in higher zoom tiles.
I think it could be generalized that the existence of the tag "highway" should be necessary for the rendering of a "way" as a part of the trail.

**Comment by lonvia** [comment]
This is a data error. Huts and similar amenities do not belong into a hiking relations. I have very strong opinions on that.

**Comment by sebicodes** [comment]
I agree completely. But: I just stopped my urge to vastly delete these huts from the relations (best automatically, just at once) because:
I would do that as correcting for the rendering. 
-> And in that case I think about the question, whether it is a good thing to render a line that is not a highway=* as a trail.
On the other hand I know that there are other people who have very strong opinions on putting many things in route relations... And I wouldn't start that edit war. (Especially not in that area where the mountains are full of the scars of the real wars. ;-) )
