### ISSUE TITLE
Ascents and descents

### ISSUE THREAD

**Issue by mic140** [waymarkedtrails/waymarked-trails-site#441]
If you compare the elevation graph and the general values of ascents and descents, you will notice their obvious discrepancy.  Can this be fixed somehow?
 Route link: https://mtb.waymarkedtrails.org/#route?id=16294949&map=15.0/53.8944/27.4715
![IMG_20230911_091818](https://github.com/waymarkedtrails/waymarked-trails-site/assets/69987154/379a201c-33f0-464a-946c-83d9d64d3486)

**Comment by lonvia** [comment]
waymarkedtrails uses a source for altitudes with a rather low resolution. That means that ascent/descent are somewhat approximate. For a route as flat as this one, it is close to impossible to distinguish between real ascents and noise. So unless we get better altitude profiles, this is a won't fix, I'm afraid.

**Comment by mic140** [comment]
But somehow you were able to construct a height graph that fully corresponds to reality.  The question was why the total ascents and descents do not correspond to the schedule.
