### ISSUE TITLE
Do not show the key "note" at the top of the relation tab

### ISSUE THREAD

**Issue by amadvance** [waymarkedtrails/waymarked-trails-site#443]
In the information tab of a relation, the tag "note" is shown at the top, like it's a description of the relation. 

Example: https://hiking.waymarkedtrails.org/#route?id=1222214

![note](https://github.com/waymarkedtrails/waymarked-trails-site/assets/747159/08374f8f-4533-47aa-9d6b-e64f78da6492)

But in OpenStreetMap, such tag "note" is intended only for other mappers. Only the tag "description" is intended for the end users. 

This extra information is not useful for the end users, and could even confuse them. I would recommend to not show it in that place.  It's instead fine to have it in the bottom part, together with other raw tags.

Here are some quotes from the OpenStreetMap documentation for reference:

_"A note is used to inform other mappers about non-obvious information about an element, the author's intent when creating it, or hints for further improvement"_
From: https://wiki.openstreetmap.org/wiki/Key:note

_"The description=* tag can be used to provide additional information about the related element to the end map user"_
From: https://wiki.openstreetmap.org/wiki/Key:description

Thanks,
Andrea

**Comment by lonvia** [comment]
waymarkedtrails always was intended as a tool for mappers. That's why the note is so prominently shown.

If the CAI would want a end-user version of the site, then lets chat.
