### ISSUE TITLE
Inactive links in help section

### ISSUE THREAD

**Issue by stalkerGH** [waymarkedtrails/waymarked-trails-site#445]
Hello.

I want to read some links from help but some of them are inactive (404). 

Examples: 

https://hiking.waymarkedtrails.org/rendering/hikinglocal
https://hiking.waymarkedtrails.org/rendering/osmc

**Comment by lonvia** [comment]
Those are links from former versions of waymarkedtrails. There are no plans to provide redirects. All documentation is still reachable from the website propoer.
