### ISSUE TITLE
Tricolor markings

### ISSUE THREAD

**Issue by stalkerGH** [waymarkedtrails/waymarked-trails-site#446]
I'd like to ask about tricolor markings. I think I'll do the best pointing to my post on OSM Community Forum with proposal presented by one of the users: https://community.openstreetmap.org/t/how-to-tag-tricolor-trails/104998

Is it possible to implement such marking in WMT too?

**Comment by Hufkratzer** [comment]
There was a discussion about second foreground a while agp: https://github.com/waymarkedtrails/waymarked-trails-site/issues/354

**Comment by stalkerGH** [comment]
Thanks. I see it is more complex than it looked at first.

**Comment by lonvia** [comment]
I've answered on community. Closing here for now, as it needs a discussion about the syntax of `osmc:symbol` first.
