### ISSUE TITLE
Render contact:*= tags

### ISSUE THREAD

**Issue by debyos** [waymarkedtrails/waymarked-trails-site#447]
Dear all,

you might consider to render not only the `website=*` tag but also `contact:website=*` and, potentially, also other ones, e.g. `contact:facebook=*` for hiking routes.
Thanks

_Gábor_

**Comment by lonvia** [comment]
I'd rather not get into that particular tag fight. There are 26k `website` tags vs. 200 `contact:website`. The majority of the latter seem to be a link to a site about the route itself rather than about a contact for the route. Let's stay with the majority tag.
