### ISSUE TITLE
Web interface prints `null` if the `ref` key is missing on a relation

### ISSUE THREAD

**Issue by amadvance** [waymarkedtrails/waymarked-trails-site#448]
Web interface prints `null` if the `ref` key is missing on a relation.

For example, consider this relation: https://hiking.waymarkedtrails.org/#route?id=16516476

It shows as:

![Screenshot 2023-11-15 at 20-58-48 Waymarked Trails - Hiking](https://github.com/waymarkedtrails/waymarked-trails-site/assets/747159/82e21993-52ec-46b4-b127-fee5ef932b41)

**Comment by lonvia** [comment]
Fixed in https://github.com/waymarkedtrails/waymarkedtrails-api/commit/81d8c2c36107e02f195d2e737ed0a97c0d37a868.
