### ISSUE TITLE
The site has been very slow on a PC recently

### ISSUE THREAD

**Issue by MFCON** [waymarkedtrails/waymarked-trails-site#451]
Accessing waymarkedtrails on my PC (Chrome/Windows 10), the site is struggling when you zoom in, and when you move around the map, I find myself having to constantly refresh the page to see the mapping.
Open Street Map itself is working normally, and I'm having no issues accessing waymarkedtrails on my phone either.
Regards

**Comment by lonvia** [comment]
What version of Chrome do you use? Can you please open the debugging console and see if there are any errors reported?

**Comment by lonvia** [comment]
Never mind, I see that there is an issue with the GeoJSON.

**Comment by MFCON** [comment]
OK, thanks. My Chrome is up to date (120.0.6099.200)

**Comment by lonvia** [comment]
Fixed the GeoJSON bug with https://github.com/waymarkedtrails/waymarkedtrails-api/commit/e915aea2a275179067c4f379664260d74d8d5332

Does this also fix the slowness for you?

**Comment by MFCON** [comment]
Working perfectly again, thanks!
