### ISSUE TITLE
no more routes in sweden : bug ? 

### ISSUE THREAD

**Issue by tolosa31** [waymarkedtrails/waymarked-trails-site#455]
I notice no more cycling routes north of gotenburg 

I cycle there last year and I know there are 2 eurovelo route 3 and 12 
I already have download  those route from your website 

screen shot in december 

![431889435_718316600461169_2275512200485334301_n](https://github.com/waymarkedtrails/waymarked-trails-site/assets/74071826/d4d234ac-3a73-4c32-93e7-54d89ee32d4d)

I contact first opensteet map and for them evrything OK so maybe cyclwaymarkedtrail issue ? 

![Screenshot_20240318_075415](https://github.com/waymarkedtrails/waymarked-trails-site/assets/74071826/52926100-27f1-4e2c-ae5b-b954a01d44b2)

normal map on osmand app 

![429516973_1052669909139021_1254813649108066487_n](https://github.com/waymarkedtrails/waymarked-trails-site/assets/74071826/cf5c8210-18db-42c7-bdd8-e33d22ca11fe)

thank you

**Comment by lonvia** [comment]
Somebody has switched the state of the route to 'proposed'.  Proposed routes are not shown in waymarkedtrails. Please start a discussion at the [appropriate changeset](https://www.openstreetmap.org/changeset/142548152) and/or at the [Swedish forum](https://community.openstreetmap.org/c/communities/se/49).

Closing here as being a data issue.
