### ISSUE TITLE
Render running routes

### ISSUE THREAD

**Issue by pyrog** [waymarkedtrails/waymarked-trails-site#456]
[route=running](https://wiki.openstreetmap.org/wiki/Tag:route%3Drunning) should be displayed in hiking style for the moment.
And better they could be rendered in their own style later.

See https://github.com/waymarkedtrails/waymarked-trails-site/issues/219#issuecomment-1016654759, https://github.com/waymarkedtrails/waymarked-trails-site/issues/396#issuecomment-2017786450 and https://github.com/waymarkedtrails/waymarked-trails-site/issues/408#issuecomment-1012014995

**Comment by lonvia** [comment]
Opening more and more issues won't make this happen any faster. The hiking map is already too full as it is.

Closing as duplicate of #219.
