### ISSUE TITLE
No relation details clicking the route on the map

### ISSUE THREAD

**Issue by BrunoItaly** [waymarkedtrails/waymarked-trails-site#457]
Hello,
I recently created several hiking route relations on OSM for CAI (Italian alpine Club) and all of them are correctly visible on waymarkedtrails  but  one of them has a problem: clicking  the  track on the map doesn't show the relation details (clicking on the track does nothing).

If you access the data through the waymarkedtrails  route  link  the data are present  and seems complete and correct.

https://hiking.waymarkedtrails.org/#route?id=17371893 

The only problem is that clicking the track on the  map doesn't open the relation window.
I'm using Chrome (but tried also firefox) and cleared the  cache several times.

What can be wrong ? Somebody can help me to understand why this happen?

PS. The route is framed using the link below, it is a red dashed lined marked "548"

https://hiking.waymarkedtrails.org/#?map=15.0/42.8282/13.3568

**Comment by lonvia** [comment]
I can confirm that I can reproduce the problem on the current site.

I'm in the middle of rolling out a new version of the site. So lets wait and see if the problem persists.

**Comment by BrunoItaly** [comment]
Just for your info,  the relation 17371893,  mentioned in my post, now works correctly but another one that I created today has the same problem.  
Did You do something to fix the first problem or it's just a matter of waiting some time ?

**Comment by lonvia** [comment]
Nothing has changed yet. I was not able to do the upgrade after all and likely won't have time in the next weeks. Sorry.

**Comment by lonvia** [comment]
Looks to be a frontend problem. The browser debugger shows calls to https://hiking.waymarkedtrails.org/api/v1/list/segments?bbox=undefined&relations=12113586,12164432,12168501,12168502,14598718,13050898,12168500

**Comment by lonvia** [comment]
Fixed with https://github.com/waymarkedtrails/waymarkedtrails-api/commit/7e344b8c41059bffb1e4e7a9666111229cdf9e5e
