### ISSUE TITLE
Parts of longer hiking routes do not render

### ISSUE THREAD

**Issue by debyos** [waymarkedtrails/waymarked-trails-site#461]
[On the map](https://hiking.waymarkedtrails.org/#?map=10.0/46.3613/25.5986), section [nr. 50](https://www.openstreetmap.org/relation/4677546#map=13/46.3739/25.4165) of [Mária-út](https://www.openstreetmap.org/relation/4646510) do not render.
Strangely, the parent relation, [Mária-út](https://hiking.waymarkedtrails.org/#route?id=4646510) can be seen entirely but its part not.
On [a lower zoom level it seems as if no section would be there](https://hiking.waymarkedtrails.org/#?map=8.0/46.3613/25.5986).

The same issue applies also to other relations e.g. to Via Transilvanica: only [6 sections can be seen on waymarkedtrails](https://hiking.waymarkedtrails.org/#route?id=12165014&type=relation) however, [it has 7 sections](https://www.openstreetmap.org/relation/12165014).

**Comment by lonvia** [comment]
The new version of the backend seems to be loosing routes because it can't find its members. Investigating...

**Comment by lonvia** [comment]
Should be back to normal now.
