### ISSUE TITLE
Routes are invisible on the map, but still present in the Routelist

### ISSUE THREAD

**Issue by ghost** [waymarkedtrails/waymarked-trails-site#465]
On the hiking.waymarkedtrails.org site and on sites where this view is used (for instance https://brouter.damsy.net/) the routes are no longer visible on the map. The map itself is still visible and the routelist also shows the routes available in the area. Problem occurs both in Chrome (127.0.6533.100) and Edge (127.0.2651.86 )
![Naamloos](https://github.com/user-attachments/assets/45c0066f-beb7-4b2a-b676-0303588441e9)

**Comment by TryIoT** [comment]
Same for cycling. Tested it on Android/chrome too.

**Comment by soshial** [comment]
I also encountered the problem

**Comment by mryx007** [comment]
also Firefox

**Comment by alex9099** [comment]
Seems like the server is giving back error 500

One of the erroring tiles https://tile.waymarkedtrails.org/hiking/4/3/7.png

**Comment by flenzen** [comment]
Apparently, also many other services like brouter overlays and opentopomaps are affected.

**Comment by lonvia** [comment]
Sorry, I was afk. Should be working again now.
