### ISSUE TITLE
Ordering of sections in super-routes

### ISSUE THREAD

**Issue by jschleic** [waymarkedtrails/waymarked-trails-site#65]
In what order are the sections of super-routes currently displayed? It would be nice, if they are displayed in the same ordering they have in the planet database.

Example:
http://cycling.lonvia.de/en/relation/2944
whereas in the underlying data the subsections are in ascending order: http://www.openstreetmap.org/browse/relation/2944

**Comment by pyrog** [comment]
It seem that #86 is broken ?
Sub relations are still ordered alphabetically 😥

Example: [relation 10720894](https://hiking.waymarkedtrails.org/#route?id=10720894)
<img width="33%" valign=top src="https://user-images.githubusercontent.com/2158081/128471973-92de38a5-73ef-4804-91af-07c0368f6b20.jpg"> <img width="33%" valign=top src="https://user-images.githubusercontent.com/2158081/128471992-ff15a03d-3852-4bc0-84cf-0392e1606240.jpg">
