### ISSUE TITLE
embed support

### ISSUE THREAD

**Issue by dittaeva** [waymarkedtrails/waymarked-trails-site#67]
Direct linking is working pretty well now. However, many times you'd want to show the map and route directly on your own homepage, blog, etc. directly, so that you can refer to it directly.

Typical use cases are:
- Blog post about a hike I've done.
- Hiking association or other association presenting the routes they manage.
- Tourist business presenting hiking opportunities nearby.
- Festival or other event presenting hiking opportunities.

This seems to be best achievable by supporting iframes. So that the user (in the uses cases) can insert, f. ex. `<iframe src="http://waymarkedtrails.org/nn/relation/1781526" style="width: 90%; height: 300px"></iframe>` into his webpage and it  will display the route relation 1781526 customised for an iframe.

You can do this today already, but then the Waymarked Trails header and the buttons will clutter the view, all links will open inside the iframe, and there's no obvious link telling us that this content comes from Waymarked Trails. In other words, it isn't customised for the iframe.

Support for the [route info view](http://waymarkedtrails.org/nn/relation/1781526) is most important, route list and map view could be added later.

A route info in an iframe should probably have the following adaptations:
- Remove Waymarked Trails header, but add link/or button of some kind to go to show that the content is from Waymarked Trails and to go there.
- Links should no open in Waymarked Trails.
- Remove the buttons, keep the zoom bar.

Iframe support could first be documented on the help pages, and later be added to a "sharing" button together with the gpx download.

Not sure how this could be best coded, but there are at least to django add-ons that looks like they could be useful: [django-iframed](https://github.com/abersager/django-iframed) and [django-iframetoolbox](https://pypi.python.org/pypi/django-iframetoolbox/0.2.1), for the first there is also a [blog post](http://oliverspindler.com/articles/2012/06/06/abominable-iframe/).

**Comment by lonvia** [comment]
You can now get the route as a geojson or gpx directly via the API and display that on your home page. This should be good enough.
