### ISSUE TITLE
Collect mapper information in "mapper" section in the route browser?

### ISSUE THREAD

**Issue by dittaeva** [waymarkedtrails/waymarked-trails-site#80]
I've always seen Waymarked Trails as a service for the general (route interested) public with extras for the active mappers of OSM, and I think it is good that way.

These extras are currently the link to the the relation on OSM on the top of the route information view and the tags section in the route information view. In issue #79 @jschleic suggests that we also link to [OSM relation analyser](http://ra.osmsurround.org) (RA) which I think is a good idea, which made me think that perhaps the mapper specific elements should have their own section on the bottom?

While the elevation profile and way distribution parts of RA could be interesting to a non-mapper, the service is definitely geared towards mappers, so I'd suggest it go into a mappers section.

The section could be headed by "OpenStreetMap contributor tools", "Details", or "Mapping tools", and could contain a link to the relation on OSM, a link to the relation on RA, editor links and the tags section as a sub-section. It could also be introduced with a small text about OpenStreetMap and "you can contribute".

**Comment by lonvia** [comment]
Closing this. I'd rather have some route analysis directly on waymarkedtrails. But that is a distance future feature.
